#### **Introduction to Tensors**
- Creating tensors

In [41]:
import torch

---

- Scaler (Normal value)

In [42]:
# Scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [43]:
# dimension of scaler
scaler.ndim

0

In [44]:
# tensor() takes 1 positional argument but 2 were given
scaler = torch.tensor(7,8)
scaler

TypeError: tensor() takes 1 positional argument but 2 were given

In [ ]:
# dimension of scaler
scaler.ndim

0

In [ ]:
# Get tensor back as Python int
scaler.item()

7

---

- Vector (1D array)

In [ ]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

---
- MATRIX (2D array)

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,6]])
MATRIX

tensor([[7, 8],
        [9, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([9, 6])

---
- Tensor (3D array)

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

---
- **Random tensors**

Why random tensors?

Random tensors are important because the way neural network learn is that they start with tensors full of random numbers and then adjust  those random numbers to better represent the data.

`Strat with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7618, 0.8226, 0.3718, 0.6560],
        [0.5963, 0.4418, 0.4378, 0.3535],
        [0.1793, 0.2537, 0.2251, 0.9447]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [45]:
torch.rand(3,3) # torch.rand(size=(3,3)) -> same

tensor([[0.2952, 0.9759, 0.7994],
        [0.5230, 0.5841, 0.7295],
        [0.2747, 0.0066, 0.0583]])

- Zeros and Ones

In [46]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
zeros = torch.zeros(size=(3,4)) * torch.rand(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [50]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [51]:
ones.dtype

torch.float32

---
- Creating a range of tensors and tensors like

In [54]:
# Use torch.range()
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# Even numbers
torch.arange(2, 20, 2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
# Odd numbers 
torch.arange(1, 20, 2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [63]:
one_to_ten = torch.arange(1, 11)
one_to_ten 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

---
- **Tensor datatypes**

**Note:** Tensor datatypes is one of the 3 big errors I'll run into with PyTorch & DeepLearning  
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the rith device 

In [67]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0])
float_32_tensor

tensor([3., 4., 5.])

In [68]:
float_32_tensor.dtype

torch.float32

In [73]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device='cpu', # what device is your tensor on 
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 4., 5.])

In [75]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [78]:
x_16_str = '16'
y_16_int = int(x_16_str)
y_16_int , type(y_16_int)

(16, int)