#### **Introduction to Tensors**
- PyTorch Version & CPU availability

In [ ]:
import torch 
print(torch.__version__)
print(torch.cuda.is_available())  # Should print False (since it's CPU only)

2.5.1
False


- #### **Creating Tensor**

---

- Scaler (Normal value)

In [8]:
# Scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
# dimension of scaler
scaler.ndim

0

In [ ]:
# tensor() takes 1 positional argument but 2 were given
scaler = torch.tensor(7,8)
scaler

TypeError: tensor() takes 1 positional argument but 2 were given

In [ ]:
# dimension of scaler
scaler.ndim

0

In [ ]:
# Get tensor back as Python int
scaler.item()

7

---

- Vector (1D array)

In [ ]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

---
- MATRIX (2D array)

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,6]])
MATRIX

tensor([[7, 8],
        [9, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([9, 6])

---
- Tensor (3D array)

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

---
- **Random tensors**

Why random tensors?

Random tensors are important because the way neural network learn is that they start with tensors full of random numbers and then adjust  those random numbers to better represent the data.

`Strat with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7618, 0.8226, 0.3718, 0.6560],
        [0.5963, 0.4418, 0.4378, 0.3535],
        [0.1793, 0.2537, 0.2251, 0.9447]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3,3) # torch.rand(size=(3,3)) -> same

tensor([[0.2952, 0.9759, 0.7994],
        [0.5230, 0.5841, 0.7295],
        [0.2747, 0.0066, 0.0583]])

- Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros = torch.zeros(size=(3,4)) * torch.rand(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

---
- Creating a range of tensors and tensors like

In [ ]:
# Use torch.range()
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Even numbers
torch.arange(2, 20, 2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Odd numbers 
torch.arange(1, 20, 2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

---
- **Tensor datatypes**

**Note:** Tensor datatypes is one of the 3 big errors I'll run into with PyTorch & DeepLearning  
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the rith device 

In [ ]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0])
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device='cpu', # what device is your tensor on 
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
x_16_str = '16'
y_16_int = int(x_16_str)
y_16_int , type(y_16_int)

(16, int)

- **Tensor Attribute**

In [5]:
import torch

In [6]:
int_32_tensor = torch.tensor([3, 4, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 9], dtype=torch.int32)

In [7]:
float_64_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=torch.float64)
float_64_tensor

tensor([3., 4., 9.], dtype=torch.float64)

In [8]:
int_32_tensor * float_64_tensor

tensor([ 9., 16., 81.], dtype=torch.float64)

---
**Getting information from tensors** (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get a shape from a tensor, can use `tensor.shape`
3. Tensors not on the rith device - to get device from a tensor, can use `tensor.device`

In [9]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2766, 0.5611, 0.0193, 0.6723],
        [0.6608, 0.9937, 0.2027, 0.4360],
        [0.3890, 0.4630, 0.1451, 0.7049]])

In [10]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.dtype}")

tensor([[0.2766, 0.5611, 0.0193, 0.6723],
        [0.6608, 0.9937, 0.2027, 0.4360],
        [0.3890, 0.4630, 0.1451, 0.7049]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: torch.float32


---
**Manipulating Tensors** (tensor operations)  
Tensor operations include:
* Addition
* Subtration
* Multiplication (element-wise)
* Division
* Matrix multiplication 

In [11]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [12]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [13]:
tensor - 10

tensor([-9, -8, -7])

In [14]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [15]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

---
**Matrix multiplication** (dot product)

In [18]:
# Element wise multiplication
print(tensor)
print(tensor * tensor)

tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor) # it is a vector dot product.
# Explanation 
# tensor = [1, 2, 3] which is 1x3 Matrix 
# we are doing --> tensor * tensor

tensor(14)

In [20]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value 

CPU times: total: 0 ns
Wall time: 14.2 ms


tensor(14)

In [21]:
%%time 
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

---
#### **Matirx multiplication** rules
* Column of first matrix must be equal to row of first matrix (Inner dimensions must match)
- `(2x3)` @ `(3x2)` will work
- `(2x3)` @ `(2x3)` won't work
* Resulting matrix has the shape of the **outer dimensions**
- `(2x3)` @ `(3x2)` -> `(2x2)` 

In [22]:
torch.matmul(torch.rand(3,4),torch.rand(4,5))

tensor([[0.8824, 1.0467, 1.2877, 1.0658, 1.1210],
        [1.1464, 1.6138, 1.9762, 1.6080, 1.4860],
        [0.8588, 0.9103, 0.9717, 0.9994, 0.9310]])

---
- One of the most common errors in deep learning: shape errors

In [24]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [25]:
tensor_a = torch.rand(3,2)
tensor_b = torch.rand(3,2)
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [26]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

---
#### Transpose matrix
- To fix our tensor shape issues, we can manipulate the shape of one of our tensor using `transpose.`
- A `transpose` switches the axes or dimensions of a given tensor.

In [27]:
tensor_b.T, tensor_b

(tensor([[0.1176, 0.0554, 0.2934],
         [0.9690, 0.4066, 0.7979]]),
 tensor([[0.1176, 0.9690],
         [0.0554, 0.4066],
         [0.2934, 0.7979]]))

In [28]:
tensor_b.shape, tensor_b.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [33]:
torch.matmul(tensor_a, tensor_b.T).shape

torch.Size([3, 3])