- super method in child class.

In [3]:
class Animal:
    def __init__(self, name):
        self.name = name
        print(f"Animal created with name: {self.name}")

class Dog(Animal):
    def __init__(self, name, breed):
        super().__init__(name)  # Call the parent class's constructor
        self.breed = breed
        print(f"Dog created with breed: {self.breed}")

# Creating a Dog instance
d = Dog("Buddy", "Golden Retriever")

Animal created with name: Buddy
Dog created with breed: Golden Retriever


> Explanation: In the Dog class, `super().__init__(name)` calls the `__init__()` method of its parent class, which is Animal.

In [ ]:
import torch
torch.manual_seed(42)
random_int = torch.randint(0, 5, size = [2])
random_int

tensor([2, 2])

In [ ]:
random_int = torch.randint(0, 10, size = [3])
random_int

tensor([6, 4, 6])

In [ ]:
random_int = torch.randint(0, 10, size = [3, 2])
random_int

tensor([[5, 0],
        [4, 0],
        [3, 8]])

In [ ]:
random_int = torch.randint(0, 10, size = (2, 3))
random_int

torch.Size([2, 3])

In [27]:
random_int_y = torch.randint(0, 7, size = [1])
random_int_y.shape

torch.Size([1])

In [25]:
random_int_x = torch.randint(0, 7, size = (1, ))
random_int_x.shape

torch.Size([1])

In [ ]:
# Create a list
numbers = [10, 20, 30, 40]

# Create an iterator from the list
iterator = iter(numbers)

# Get the first item using next()
first_number = next(iterator)
second_number = next(iterator)

print(f"First number: {first_number}")  # Outputs: First number: 10
print(f"Second number: {second_number}")  # Outputs: Second number: 20

In [29]:
# Create a iterable list 
numbers = [1, 2, 3]

# Create an iterator from the list 
iterator = iter(numbers)
print(next(iterator))
print(next(iterator))
print(next(iterator))

1
2
3
