In [1]:
from sklearn.datasets import make_classification

# create custom classification dataset
X, y = make_classification(
    n_samples=100,
    n_features=5,
    n_informative=5,
    n_redundant=0,
    n_classes=3
)

In [2]:
print(X[:4]); print(); print(X.shape)

[[ 0.31295794  1.08838527 -0.80163483  0.33515134  1.07489266]
 [-0.03806003 -0.34921843 -2.80981522 -3.51861763 -1.80040764]
 [-0.93074383  1.71560387  0.1444574  -1.68081544  1.33434285]
 [ 0.78478791 -2.35029224  1.76015616  2.48997865  1.67067319]]

(100, 5)


In [3]:
print(y[:5]); print(); print(y.shape)

[1 2 0 0 0]

(100,)


In [4]:
# Convert numpy array to pytorch tensor
import torch
X_train = torch.tensor(X, dtype=torch.float32)
y_train = torch.tensor(y, dtype=torch.long)

In [5]:
print(X_train[:4])

tensor([[ 0.3130,  1.0884, -0.8016,  0.3352,  1.0749],
        [-0.0381, -0.3492, -2.8098, -3.5186, -1.8004],
        [-0.9307,  1.7156,  0.1445, -1.6808,  1.3343],
        [ 0.7848, -2.3503,  1.7602,  2.4900,  1.6707]])


In [6]:
print(y_train[:4])

tensor([1, 2, 0, 0])


In [7]:
# Now create our custom dataset
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [8]:
dataset = CustomDataset(X_train, y_train)

In [9]:
print(len(dataset))

100


In [10]:
dataLoader = DataLoader(
    dataset,
    batch_size=5,
    shuffle=True
)

In [11]:
for batch_features, batch_labels in dataLoader:
    print(batch_features)
    print(batch_labels)
    print("-" * 60)

tensor([[ 1.7064, -0.5429,  0.3804, -1.8054, -0.1801],
        [ 0.9438,  1.3105,  0.2398, -0.4022, -1.1473],
        [-2.5340,  0.6960, -2.1478,  0.4456,  1.4277],
        [ 1.9475, -1.2192, -1.9107, -5.7112, -0.5817],
        [-0.4083,  2.0467,  0.6026, -2.1528,  2.7736]])
tensor([0, 2, 0, 0, 0])
------------------------------------------------------------
tensor([[ 0.7848, -2.3503,  1.7602,  2.4900,  1.6707],
        [ 0.8421, -0.7365,  1.1758, -1.6590,  0.6603],
        [ 1.2062, -1.6272,  1.6323,  0.7129,  2.1320],
        [-1.4872, -0.9793, -0.8400,  1.6811,  0.5549],
        [ 1.0513,  0.2043, -2.8430, -3.7137, -0.9366]])
tensor([0, 0, 0, 1, 2])
------------------------------------------------------------
tensor([[ 1.5402, -1.4023,  0.4009, -1.3361,  0.9540],
        [-1.0333,  1.1465, -4.0218,  1.2609, -3.2467],
        [-0.0049, -0.1977, -0.0948,  2.1375,  0.0546],
        [ 0.1988,  0.9918,  1.3893, -1.5579,  0.5255],
        [ 0.0335,  1.5424,  3.3761, -0.2720,  1.6022]])
te

### **Joss**