In [1]:
from sklearn.datasets import make_classification

# create custom classification dataset
X, y = make_classification(
    n_samples=100,
    n_features=5,
    n_informative=5,
    n_redundant=0,
    n_classes=3
)

In [2]:
print(X[:4]); print(); print(X.shape)

[[-0.66908547  0.1965899   2.32451917 -2.32147356  0.34729516]
 [-1.12867475  1.59393101  1.4965773  -1.32763045 -0.43884541]
 [-2.94375137 -1.29122747  2.88149092  3.47214077  1.71858626]
 [-0.03397882  1.74742965 -0.59531995  0.72239527  0.50992799]]

(100, 5)


In [3]:
print(y[:5]); print(); print(y.shape)

[0 0 1 0 1]

(100,)


In [4]:
# Convert numpy array to pytorch tensor
import torch
X_train = torch.tensor(X, dtype=torch.float32)
y_train = torch.tensor(y, dtype=torch.long)

In [5]:
print(X_train[:4])

tensor([[-0.6691,  0.1966,  2.3245, -2.3215,  0.3473],
        [-1.1287,  1.5939,  1.4966, -1.3276, -0.4388],
        [-2.9438, -1.2912,  2.8815,  3.4721,  1.7186],
        [-0.0340,  1.7474, -0.5953,  0.7224,  0.5099]])


In [6]:
print(y_train[:4])

tensor([0, 0, 1, 0])


In [7]:
# Now create our custom dataset
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]


In [8]:
dataset = CustomDataset(X_train, y_train)

In [9]:
print(len(dataset))

100


In [10]:
dataLoader = DataLoader(
    dataset,
    batch_size=5,
    shuffle=True
)

In [11]:
for batch_features, batch_labels in dataLoader:
    print(batch_features)
    print(batch_labels)
    print("--" * 50)

tensor([[ 0.3953,  2.2995, -1.4151, -0.3909,  1.3512],
        [ 0.5605,  2.5458, -0.1730,  1.3082,  1.0443],
        [-2.9438, -1.2912,  2.8815,  3.4721,  1.7186],
        [-0.9527,  1.4476, -0.7587,  1.2500,  0.6926],
        [-0.0340,  1.7474, -0.5953,  0.7224,  0.5099]])
tensor([1, 1, 1, 0, 0])
----------------------------------------------------------------------------------------------------
tensor([[-1.8183, -0.2084,  0.6239,  2.1716,  1.7458],
        [-1.7132,  0.9766,  1.5886,  1.5415,  0.9865],
        [-1.2200, -0.8856,  0.1396,  1.0314, -1.4111],
        [ 0.3658,  2.7777,  2.7708, -1.4847,  0.0454],
        [-0.8056,  0.2304,  1.6330, -1.7456, -1.3405]])
tensor([1, 1, 1, 0, 0])
----------------------------------------------------------------------------------------------------
tensor([[-0.5739,  1.7993,  0.4199,  0.0133, -1.2105],
        [-1.0051,  1.3958,  0.5648,  1.1580,  0.2248],
        [-1.2664,  0.0077,  0.4159,  1.1699, -0.5481],
        [ 0.3760, -1.3957, -0.918

### **Joss**