### **Tensors in Pytorch:**

If you ever stuck, see this tutorail:  
https://www.learnpytorch.io/00_pytorch_fundamentals/ 


- Tensors are the fundamental of building block of Machine Learning & Deep learning.

In [15]:
import torch
torch.__version__

'2.6.0+cpu'

In [16]:
# create a scalar [zero dimension tensor]
scalar = torch.tensor(7) # np.array (kind of)
print(scalar)

tensor(7)


In [17]:
# dimension & shape of scalar
print(f"Dimension of scalar: {scalar.ndim}")
print(f"Shape of scalar   : {scalar.shape}")

Dimension of scalar: 0
Shape of scalar   : torch.Size([])


In [18]:
# type of scalar
print(f"Type of scalar: {type(scalar)}")

Type of scalar: <class 'torch.Tensor'>


In [19]:
# what if we wanted to retrive the number from the tensor.
# torch.Tensor to a Python integer.
# get the python numer within a tensor
scalar_x = scalar.item() # (only works with one-element tensors)
print(f"It's a python integer now   : {scalar_x}")
print(f"Type of the scalar_x        : {type(scalar_x)}")

It's a python integer now   : 7
Type of the scalar_x        : <class 'int'>


In [20]:
# not works with list
li = [10, 20, 30]
x = li.item()
print(x)

AttributeError: 'list' object has no attribute 'item'

In [21]:
import numpy as np
import torch
import tensorflow as tf

# NumPy
arr = np.array([1, 2, 3])
# arr.item()  # Fails: ValueError
print(arr[0].item())  # Works: 1
print(arr.tolist())   # Works: [1, 2, 3]

# PyTorch
tensor = torch.tensor([1, 2, 3])
# tensor.item()  # Fails: ValueError
print(tensor[0].item())  # Works: 1
print(tensor.tolist())   # Works: [1, 2, 3]

# TensorFlow
tf_tensor = tf.constant([1, 2, 3])
# tf_tensor.numpy().item()  # Fails: ValueError
print(tf_tensor[0].numpy().item())  # Works: 1
print(tf_tensor.numpy().tolist())   # Works: [1, 2, 3]

1
[1, 2, 3]
1
[1, 2, 3]
1
[1, 2, 3]


In [22]:
# create a vector 
# vector is a one dimensional array
vector = torch.tensor([4, 7, 4, 1])
print(f"Vector              : {vector}")
print(f"Dimension of vector : {vector.ndim}")
print(f"Shape of vector     : {vector.shape}")

Vector              : tensor([4, 7, 4, 1])
Dimension of vector : 1
Shape of vector     : torch.Size([4])


In [23]:
# create a matrix 
# Matrix is a 2D array
MATRIX = torch.tensor([[1, 3, 2,], [6, 5, 4]])
print(f"Matrix              : \n{MATRIX}")
print(f"Dimension of matrix : {MATRIX.ndim}")
print(f"Shape of matrix     : {MATRIX.shape}")

Matrix              : 
tensor([[1, 3, 2],
        [6, 5, 4]])
Dimension of matrix : 2
Shape of matrix     : torch.Size([2, 3])


In [24]:
# create a tensors 
# Tensors are multidimensional array
TENSOR = torch.tensor([[[4, 7, 4], [3, 6, 9]],[[4, 7, 4], [3, 6, 9]]])
print(f"Tensor              : \n{TENSOR}")
print(f"Dimension of tensor : {TENSOR.ndim}")
print(f"Shape of tensor     : {TENSOR.shape}")

# ekhane bujhacche je 1 ta 2x3 Matrix ache 
torch.Size([1, 2, 3])

Tensor              : 
tensor([[[4, 7, 4],
         [3, 6, 9]],

        [[4, 7, 4],
         [3, 6, 9]]])
Dimension of tensor : 3
Shape of tensor     : torch.Size([2, 2, 3])


torch.Size([1, 2, 3])

In [25]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
print(f"Random tensor: \n{random_tensor}")

Random tensor: 
tensor([[0.3210, 0.1679, 0.0033, 0.1012],
        [0.2298, 0.8034, 0.8795, 0.0429],
        [0.5509, 0.4799, 0.1555, 0.7998]])


In [26]:
# lest relate with numpy 
random_array = np.random.rand(3,4) # don't take size argument
print(f"Random array: \n{random_array}")

Random array: 
[[0.504012   0.58814257 0.07423403 0.51740594]
 [0.12946324 0.44772162 0.76181486 0.24645435]
 [0.21577083 0.29242429 0.92695925 0.70734118]]


In [27]:
random_sample_array =  np.random.sample(size = (3, 4))
print(f"Random sample array: \n{random_sample_array}")

Random sample array: 
[[0.7997395  0.35933257 0.3058302  0.6815087 ]
 [0.26743951 0.17486975 0.1322062  0.0332143 ]
 [0.94807338 0.00485563 0.36580519 0.72798227]]


In [28]:
# create a random  of size (224, 224, 3) which is a image size 
# (hiegt, width, color_channels)
random_image_size_tensor = torch.rand(224, 224, 3)
print(f"Shape of random image size tensor: {random_image_size_tensor.shape}")
print(f"Shape of random image size tensor: {random_image_size_tensor.ndim}")

Shape of random image size tensor: torch.Size([224, 224, 3])
Shape of random image size tensor: 3


In [29]:
# create tensor with zeros
zeros = torch.zeros((3,4))
print(f"Tensor with zeros: \n{zeros}")

Tensor with zeros: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [30]:
# create tensor with ones 
ones = torch.ones((3,4))
print(f"Tensor with ones: \n{ones}")

Tensor with ones: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [31]:
# creating a ranged tensor -> arange(start, end, step)
two_to_nine = torch.arange(2, 10, 0.5)
print(f"Two to nine vector      : {two_to_nine}")
print(f"Two to nine vector shape: {two_to_nine.shape}")

Two to nine vector      : tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000,
        6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])
Two to nine vector shape: torch.Size([16])


In [32]:
# create tensor zeros_like 
A = torch.arange(12).reshape(3, 4)
print(f"Tensor A  : \n{A}")
zeros_like = torch.zeros_like(input = A)
print(f"Zeros like: \n{zeros_like}")

Tensor A  : 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Zeros like: 
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [33]:
# create tensor ones_like 
ones_like = torch.ones_like(input = A)
print(f"Tensor A  : \n{A}")
print(f"Ones like: \n{ones_like}")

Tensor A  : 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Ones like: 
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


- Tensor datatypes  

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

In [34]:
# default datatype for tensor is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None,
                                device = None,
                                requires_grad = False)
print(f"Default data type  : {float_32_tensor.dtype}")
print(f"Default device type: {float_32_tensor.device}")

Default data type  : torch.float32
Default device type: cpu


In [35]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = torch.float16) # torch.half
print(f"Data type          : {float_16_tensor.dtype}")
print(f"Default device type: {float_16_tensor.device}")

Data type          : torch.float16
Default device type: cpu


---
**Getting information form tensors:**  

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

- `shape` - what shape is the tensor? (some operations require specific shape rules)  
- `dtype` - what datatype are the elements within the tensor stored in?  
- `device` - what device is the tensor stored on? (usually GPU or CPU)  

In [36]:
# create a tensor
M = torch.rand(3, 4)

# find out detailed about it 
print(f"Tensor : \n{M}")
print(f"Shape of tensor             : {M.shape}")
print(f"Data type of tensor         : {M.dtype}")
print(f"Device tensor is stored on  : {M.device}")

Tensor : 
tensor([[0.2224, 0.8596, 0.7314, 0.3475],
        [0.0922, 0.7076, 0.5293, 0.6832],
        [0.0216, 0.5364, 0.2689, 0.0286]])
Shape of tensor             : torch.Size([3, 4])
Data type of tensor         : torch.float32
Device tensor is stored on  : cpu


---
**Manipulating tensors (tensor operations):**

These operations are often a wonderful dance between:

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [37]:
t = torch.tensor([1, 2, 3])
print(f"Adding t + 10: {t + 10}")

Adding t + 10: tensor([11, 12, 13])


In [38]:
# for numpy
n = np.array([1, 2, 3])
print(f"Adding n + 10: {n + 10}") 

Adding n + 10: [11 12 13]


In [39]:
p = torch.tensor([1, 2, 3])
t = torch.tensor([5]) # stretched
print(f"Adding p + t : {p + t}")

Adding p + t : tensor([6, 7, 8])


In [40]:
n = np.array([1, 2, 3])
p = np.array([5]) # stretched
print(f"Adding n + p : {n + p}")

Adding n + p : [6 7 8]


In [41]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([10]) # stretched

print(f"Multiplying x * y: {x * y}")

Multiplying x * y: tensor([10, 20, 30])


In [42]:
x = torch.tensor([1, 2, 3])
y = torch.tensor(10) # stretched

print(f"Multiplying x * y: {x * y}")

Multiplying x * y: tensor([10, 20, 30])


In [43]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([10, 20]) # stretched

print(f"Multiplying x * y: {x * y}")

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

> `Note:` Same goes for Subtraction, Multiplication, Division.

**Element-wise multiplication:**

- tensor * tensor: [1 * 10, 2 * 20, 3 * 30] = [10, 40, 90]

In [44]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([10, 20, 30]) # stretched

print(f"Multiplying x * y: {x * y}")

Multiplying x * y: tensor([10, 40, 90])


In [45]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([10, 20]) # stretched

print(f"Multiplying x * y: {x * y}")

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

**Matrix multiplication:**


**Matrix Multiplication Rule:**

For two matrices `A` and `B` to be multiplied (`A @ B`), the **number of columns in A must match the number of rows in B**:

$$
\text{If } A \in \mathbb{R}^{m \times n},\ B \in \mathbb{R}^{n \times p} \Rightarrow A @ B \in \mathbb{R}^{m \times p}
$$

In [48]:
A = torch.tensor([1, 2, 3, 4, 5])
B = torch.tensor([1, 2, 3, 4, 5])
print(f"Shape of A      : {A.shape}")
print(f"Dimension of A  : {A.ndim}")
print(f"Shape of B      : {B.shape}")
print(f"Dimension of B  : {B.ndim}")
M = torch.matmul(A, B)
print(f"Matrix multiplication of A @ B: {M}")

Shape of A      : torch.Size([5])
Dimension of A  : 1
Shape of B      : torch.Size([5])
Dimension of B  : 1
Matrix multiplication of A @ B: 55



- **Matrix Multiplication Rule:**

For two matrices `A` and `B` to be multiplied (`A @ B`), the **number of columns in A must match the number of rows in B**:

$$
\text{If } A \in \mathbb{R}^{m \times n},\ B \in \mathbb{R}^{n \times p} \Rightarrow A @ B \in \mathbb{R}^{m \times p}
$$

---

**So what happens when we do this?**

```python
A = torch.tensor([1, 2, 3, 4, 5])
B = torch.tensor([1, 2, 3, 4, 5])
M = torch.matmul(A, B)
```

These are **1D tensors**:

* Shape of `A`: `[5]`
* Shape of `B`: `[5]`

Even though they *look like vectors*, under the hood, PyTorch treats them as special cases:

| Tensor | Logical View  | Shape |
| ------ | ------------- | ----- |
| `A`    | Row vector    | `[5]` |
| `B`    | Column vector | `[5]` |

So when you do `torch.matmul(A, B)`, PyTorch interprets this as a **dot product**, which mathematically is equivalent to multiplying a **1 × 5** matrix by a **5 × 1** matrix:

$$
[1\ 2\ 3\ 4\ 5] \times
\begin{bmatrix}
1 \\
2 \\
3 \\
4 \\
5 \\
\end{bmatrix}
= [55]
$$

This results in a **1×1 matrix**, i.e., a scalar value.

---

**Alternative way to see the rule in action:**

If you **explicitly reshape** the tensors:

```python
A = A.unsqueeze(0)  # Shape becomes [1, 5]
B = B.unsqueeze(1)  # Shape becomes [5, 1]

print(A.shape)  # torch.Size([1, 5])
print(B.shape)  # torch.Size([5, 1])

M = torch.matmul(A, B)
print(M)        # tensor([[55]])
print(M.shape)  # torch.Size([1, 1])
```

Here, the rule is followed exactly:

* First matrix: `1 × 5`
* Second matrix: `5 × 1`
* Result: `1 × 1`

In [59]:
n = 3.1415926535
print(f"n : {n:.4f}")

n : 3.1416


In [58]:
# Without loop 
import time

A = torch.tensor([1, 2, 3, 4, 5])
B = torch.tensor([1, 2, 3, 4, 5])
start = time.time()
M = torch.matmul(A, B)
end = time.time()
print(f"Epalpsed time without loop: {end - start:.4f} second")

Epalpsed time without loop: 0.0000 second


In [60]:
# with loop 
import time 

A = torch.tensor([1, 2, 3, 4, 5])
B = torch.tensor([1, 2, 3, 4, 5])
MatMal = 0

start = time.time()

for i in range(A.shape[0]):
    MatMal += A[i] * B[i]

end = time.time()

print(f"Epalpsed time without loop: {end - start:.4f} second")

Epalpsed time without loop: 0.0249 second



**One of the most common errors in deep learning (shape errors):**

In [61]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.  

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

In [62]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
print(f"Shape of tensor_A: {tensor_A.shape}")
print(f"Shape of tensor_B: {tensor_B.shape}")

Shape of tensor_A: torch.Size([3, 2])
Shape of tensor_B: torch.Size([3, 2])


In [64]:
tensor_B_transposed = tensor_B.T
print(f"B after transposing          : \n{tensor_B_transposed}")
print(f"Shape of tensor_A            : {tensor_A.shape}")
print(f"Shape of tensor_B_transposed : {tensor_B_transposed.shape}")

B after transposing          : 
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
Shape of tensor_A            : torch.Size([3, 2])
Shape of tensor_B_transposed : torch.Size([2, 3])


In [66]:
A_x_B = torch.matmul(tensor_A, tensor_B_transposed) # (this will error)
print(f"Multiplication after transposing: \n{A_x_B}")

Multiplication after transposing: 
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


**Implementing `nn.Linear()` module:**

In [2]:
import torch

In [ ]:
torch.manual_seed(42)
input_x = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

linear = torch.nn.Linear(in_features=2, out_features=6)
output_neurons = linear(input_x)
print(f"Input shape     : {input_x.shape}\n")
print(f"Output neurons  : \n{output_neurons}\n\n")
print(f"Output shape    : \n{output_neurons.shape}\n\n")

# input_x: (3x2), hidden layer: (2x6)
# after matmal output layer becomes 3x6


Input shape     : torch.Size([3, 2])

Output neurons  : 
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


Output shape    : 
torch.Size([3, 6])




**Finding the min, max, mean, sum, etc (aggregation)**

In [8]:
# Create a tensor 
x = torch.arange(0, 100, 10)
print(f"Vector x: {x}")

Vector x: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [17]:
# lets perform some aggregation 
print(f"Minimum : {x.min()}")
print(f"Maximum : {x.max()}")
# print(f"Mean   : {x.mean()}") # this will give an error 
# because mean function wants float argument
print(f"Mean    : {x.type(torch.float32).mean()}")
print(f"Sum     : {x.sum()}")
# print(f"Standard deviation: {x.std()}") # this will give an error 
# because std function wants float argument

print(f"Standard deviation: {x.type(torch.float32).std():.4}")

Minimum : 0
Maximum : 90
Mean    : 45.0
Sum     : 450
Standard deviation: 30.28


**Positional min/max:**

In [18]:
m = torch.tensor([50, 40, 90, 70, 10, 80, 5, 15, 30])
print(f"Index where max value occurs: {m.argmax()}")
print(f"Index where min value occurs: {m.argmin()}")

Index where max value occurs: 2
Index where min value occurs: 6


**Change tensor datatype:**

In [19]:
v = torch.arange(10., 100, 10)
print(v)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])


In [20]:
v_float16 = v.type(torch.float16)
print(f"Data type of v_float16: {v_float16.dtype}")

Data type of v_float16: torch.float16


**Reshaping, stacking, viewing, squeezing, unsqueezing & permute:**

In [23]:
# reshaping
v = torch.arange(12)
v_reshaped = v.reshape(3, 4)
print(f"Shape of v without reshaping: \n{v}")
print(f"Shape of v with reshaping   : \n{v_reshaped}")

Shape of v without reshaping: 
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape of v with reshaping   : 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [2]:
# Concatenates a sequence of tensors along a new dimension
# All tensors need to be of the same size 
import torch
x = torch.rand(2,3)
print(f"Tensor x: \n{x}")

Tensor x: 
tensor([[0.5540, 0.4768, 0.8826],
        [0.0583, 0.4924, 0.6677]])


In [4]:
x_stacked = torch.stack((x, x), dim=0)
print(f"Tensor stacked: \n{x_stacked}")

Tensor stacked: 
tensor([[[0.5540, 0.4768, 0.8826],
         [0.0583, 0.4924, 0.6677]],

        [[0.5540, 0.4768, 0.8826],
         [0.0583, 0.4924, 0.6677]]])


**Difference table of `torch.rand()` and `torch.randn()` Table:**

| Function        | Distribution      | Range       | Centered Around | Example Use Case                   |
| --------------- | ----------------- | ----------- | --------------- | ---------------------------------- |
| `torch.rand()`  | Uniform           | \[0.0, 1.0) | 0.5             | Random scaling, dropout, etc.      |
| `torch.randn()` | Normal (Gaussian) | \~(-∞, ∞)   | 0               | Weight initialization, noise, etc. |



---

**Indexing and slicing data from tensor:**

- Indexing for 3D:  
`[which_matrix, which_array, which_element]`
- Indexing for 2D:  
`[which_array, which_element]`
- Indexing for 1D:  
`[which_element]`

In [1]:
# create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
print(f"Tensor x       : \n{x}")
print(f"Tensor x shape : \n{x.shape}")

Tensor x       : 
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Tensor x shape : 
torch.Size([1, 3, 3])


In [2]:
# indexing values goes outer dimension to inner dimension
print(f"First sqaure bracket:\n{x[0]}")
print(f"Second square bracket:\n{x[0][0]}")
print(f"Third square bracket:\n{x[0][0][0]}")

First sqaure bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:
tensor([1, 2, 3])
Third square bracket:
1


In [3]:
print(f"First sqaure bracket:\n{x[0]}")
print(f"Second square bracket:\n{x[0,0]}")
print(f"Third square bracket:\n{x[0, 0, 0]}")

First sqaure bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:
tensor([1, 2, 3])
Third square bracket:
1


In [5]:
import torch
x = torch.arange(1, 19).reshape(2, 3, 3)
print(f"Tensor x       : \n{x}")
print(f"Tensor x shape : \n{x.shape}")

Tensor x       : 
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Tensor x shape : 
torch.Size([2, 3, 3])


In [8]:
# There is two matrix in the first square bracket
print(f"First matrix of the first sqaure bracket   :\n{x[0]}")
print(f"Second matrix of the second sqaure bracket :\n{x[1]}")

First matrix of the first sqaure bracket   :
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second matrix of the second sqaure bracket :
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [10]:
print(f"Second square bracket:\n{x[0,0]}")
print(f"Second square bracket:\n{x[1,0]}")

Second square bracket:
tensor([1, 2, 3])
Second square bracket:
tensor([10, 11, 12])


- Slicing vector:  `vector[start:end:step]`

In [14]:
# Lets go through lower to higher dimension 
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])

# Print all 
print(f"Printing all elements: {x[:]}")
# print all reverse 
# print(f"Printing all reverese: {x[::-1]}")
# Note: PyTorch don't support pythonic slicing reverse 
print(f"Printing 3 to 6: {x[3:7]}")

Printing all elements: tensor([1, 2, 3, 4, 5, 6, 7, 8])
Printing 3 to 6: tensor([4, 5, 6, 7])


- Slicing Matrix:  
`Matrix[start:end:step]`  
`Matrix[row:column]`
`Matrix[row_start:row_end:row_step, column_start, column_end, column_step]`

In [19]:
M = torch.arange(1,10).reshape(3,3)
print(f"Print all elements: \n{M[:]}")
print(f"Print second column: \n{M[:,1:2]}")

Print all elements: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Print second column: 
tensor([[2],
        [5],
        [8]])


In [23]:
M = torch.arange(1, 26).reshape(5,5)
print(f"Printing all columns: \n{M[:]}")
print(f"Printing column 2-4: \n{M[:,1:4]}")
print(f"Printing row 2-4: \n{M[1:4, :]}")

Printing all columns: 
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])
Printing column 2-4: 
tensor([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19],
        [22, 23, 24]])
Printing row 2-4: 
tensor([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


**PyTorch Tensor and Numpy:**

- Numpy to tensor

In [25]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)

# Convert numpy to tensor 
numpy_to_tensor = torch.from_numpy(array)
print(f"Numpy array type: {type(array)}")
print(f"Type after converting to tensor: {type(numpy_to_tensor)}")

Numpy array type: <class 'numpy.ndarray'>
Type after converting to tensor: <class 'torch.Tensor'>


- Tensor to numpy

In [26]:
import torch
import numpy as np
v = torch.arange(1.0, 6.0)

# Convert tensor to numpy
tensor_to_numpy = v.numpy()
print(f"Tesor array type: {type(v)}")
print(f"Type after converting to numpy: {type(tensor_to_numpy)}")

Tesor array type: <class 'torch.Tensor'>
Type after converting to numpy: <class 'numpy.ndarray'>


**Reproducibility:**

- Without manual seed they will change randomly:

In [36]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f"Tensor A: \n{random_tensor_A}")
print(f"Tensor B: \n{random_tensor_B}")
print(f"Does Tensor A equal to B? (anywhere)")
print(f"Checking equality: \n{random_tensor_A == random_tensor_B}")

Tensor A: 
tensor([[0.8035, 0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057, 0.3725],
        [0.7980, 0.8399, 0.1374, 0.2331]])
Tensor B: 
tensor([[0.9578, 0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340, 0.1371],
        [0.5117, 0.1585, 0.0758, 0.2247]])
Does Tensor A equal to B? (anywhere)
Checking equality: 
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [32]:
torch.manual_seed(42)
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor_B = torch.rand(3, 4)
print(f"Tensor A: \n{random_tensor_A}")
print(f"Tensor B: \n{random_tensor_B}")
print(f"Does Tensor A equal to B? (anywhere)")
print(f"Checking equality: \n{random_tensor_A == random_tensor_B}")

Tensor A: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor B: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Does Tensor A equal to B? (anywhere)
Checking equality: 
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


- Checking GPU

In [38]:
import torch
print(torch.cuda.is_available())

False


In [40]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"My device is: {device}")

My device is: cpu


In [43]:
# Count number of devices
print(f"Number of gpu: {torch.cuda.device_count()}")

Number of gpu: 0


**Putting tensors on GPU:**

In [44]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps"  # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [46]:
# Create tensor (default on CPU)
x = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(x, x.device)

# Move tensor to GPU (if availabe) [Though I don't have one😂]
x_on_gpu = x.to(device)
print(x, x.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3]) cpu


**Moving back to the CPU:**
- For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

In [47]:
# If tensor is on GPU, can't transform it to NumPy(this will error)
x_on_gpu.numpy()

array([1, 2, 3])

In [50]:
# Instead, copy the tensor back to cpu
x_back_on_cpu = x_on_gpu.cpu().numpy()
x_back_on_cpu

array([1, 2, 3])

In [51]:
x_on_gpu

tensor([1, 2, 3])