In [1]:
import torch

In [2]:
tensor_3D = torch.tensor([[[1, 2],
                          [3, 4]]])
tensor_squeezed = torch.squeeze(tensor_3D)
tensor_3D.ndim

3

In [3]:
print(f'Dimension of tensor_3D: {tensor_3D.ndim}')
print(f'Dimension of tensor_squeezed: {tensor_squeezed.ndim}')

Dimension of tensor_3D: 3
Dimension of tensor_squeezed: 2


In [4]:
x = torch.tensor([1,2,3])
x, x.shape, x.ndim

(tensor([1, 2, 3]), torch.Size([3]), 1)

In [5]:
x_unsqueezed = torch.unsqueeze(x, dim = 1)
x_unsqueezed, x_unsqueezed.shape, x_unsqueezed.ndim

(tensor([[1],
         [2],
         [3]]),
 torch.Size([3, 1]),
 2)

In [9]:
x = torch.tensor(9)
x_squeezed = torch.squeeze(x)
x_squeezed, x

(tensor(9), tensor(9))

In [ ]:
x = torch.tensor([1, 2, 3, 4])
x_unsqueezed = torch.unsqueeze(x, dim=0)
x_unsqueezed, x_unsqueezed.ndim, x, x.ndim

(tensor([[1, 2, 3, 4]]), 2, tensor([1, 2, 3, 4]), 1)

In [17]:
x = torch.tensor([1, 2, 3, 4])
x_unsqueezed = torch.unsqueeze(x, dim=1)
x_unsqueezed, x_unsqueezed.ndim, x, x.ndim

(tensor([[1],
         [2],
         [3],
         [4]]),
 2,
 tensor([1, 2, 3, 4]),
 1)

In [18]:
x = torch.tensor([[1, 2, 3, 4],
                  [1, 3, 5, 7],
                  [4, 9, 0, 1]])
x_unsqueezed = torch.unsqueeze(x, dim=0)
x_unsqueezed, x_unsqueezed.ndim, x, x.ndim

(tensor([[[1, 2, 3, 4],
          [1, 3, 5, 7],
          [4, 9, 0, 1]]]),
 3,
 tensor([[1, 2, 3, 4],
         [1, 3, 5, 7],
         [4, 9, 0, 1]]),
 2)

In [19]:
x = torch.tensor([[1, 2, 3, 4],
                  [1, 3, 5, 7],
                  [4, 9, 0, 1]])
x_unsqueezed = torch.unsqueeze(x, dim=1)
x_unsqueezed, x_unsqueezed.ndim, x, x.ndim

(tensor([[[1, 2, 3, 4]],
 
         [[1, 3, 5, 7]],
 
         [[4, 9, 0, 1]]]),
 3,
 tensor([[1, 2, 3, 4],
         [1, 3, 5, 7],
         [4, 9, 0, 1]]),
 2)