In [2]:
import torch
from torch import nn
import matplotlib.pyplot as plt

# Check Pytorch Version 
torch.__version__

# nn contains all of PyTorch's building blocks for neural networks 

'2.6.0+cpu'

---
- Tensors are the fundamental building block of machine learning 
- Their job is to represnt data in a numerical way
- we can represnt image into numbers too


#### Creating tensors

In [3]:
# Saclar tensor (Zero dimension, just a number)
scalar = torch.tensor(7)
scalar, scalar.dtype

(tensor(7), torch.int64)

In [4]:
scalar.ndim

0

- A vector is a single dimension tensor but can contain many numbers.

In [ ]:
vector = torch.tensor([7,7]) # count square brackets
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [ ]:
vector.shape # it shows the number of elements 

torch.Size([2])

In [8]:
v = torch.tensor([1,2,4,5])
v, v.ndim, v.shape

(tensor([1, 2, 4, 5]), 1, torch.Size([4]))

- MATRIX has two dimensions (did you count the number of square brackets on the outside of one side?).

In [9]:
Matrix = torch.tensor([[1,2],
                       [3,4]])

In [10]:
Matrix, Matrix.ndim, Matrix.shape

(tensor([[1, 2],
         [3, 4]]),
 2,
 torch.Size([2, 2]))

- Tensors are 3D array

In [ ]:
Tensor = torch.tensor([[[1,2,3],
                        [3,4,5]],
                        [[1,2,4],
                         [3,4,5]]])
Tensor, Tensor.ndim, Tensor.shape
# 2 ta 2x3 Matrix 

(tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[1, 2, 4],
          [3, 4, 5]]]),
 3,
 torch.Size([2, 2, 3]))