In [2]:
import torch
from torch import nn
import matplotlib.pyplot as plt

# Check Pytorch Version 
torch.__version__

# nn contains all of PyTorch's building blocks for neural networks 

'2.6.0+cpu'

---
- Tensors are the fundamental building block of machine learning 
- Their job is to represnt data in a numerical way
- we can represnt image into numbers too


#### Creating tensors

In [3]:
# Saclar tensor (Zero dimension, just a number)
scalar = torch.tensor(7)
scalar, scalar.dtype

(tensor(7), torch.int64)

In [4]:
scalar.ndim

0

- A vector is a single dimension tensor but can contain many numbers.

In [5]:
vector = torch.tensor([7,7]) # count square brackets
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape # it shows the number of elements 

torch.Size([2])

In [8]:
v = torch.tensor([1,2,4,5])
v, v.ndim, v.shape

(tensor([1, 2, 4, 5]), 1, torch.Size([4]))

- MATRIX has two dimensions (did you count the number of square brackets on the outside of one side?).

In [9]:
Matrix = torch.tensor([[1,2],
                       [3,4]])

In [10]:
Matrix, Matrix.ndim, Matrix.shape

(tensor([[1, 2],
         [3, 4]]),
 2,
 torch.Size([2, 2]))

- Tensors are 3D array

In [11]:
Tensor = torch.tensor([[[1,2,3],
                        [3,4,5]],
                        [[1,2,4],
                         [3,4,5]]])
Tensor, Tensor.ndim, Tensor.shape
# 2 ta 2x3 Matrix 

(tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[1, 2, 4],
          [3, 4, 5]]]),
 3,
 torch.Size([2, 2, 3]))

- Random tensors

In [12]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1353, 0.2986, 0.4677, 0.9807],
         [0.8048, 0.7848, 0.9440, 0.2141],
         [0.0768, 0.5876, 0.7629, 0.3093]]),
 torch.float32)

- The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

- For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [13]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor, random_image_size_tensor.ndim, random_image_size_tensor.shape

(tensor([[[0.3009, 0.6159, 0.8180],
          [0.7097, 0.3574, 0.4351],
          [0.1816, 0.4573, 0.0516],
          ...,
          [0.3679, 0.2116, 0.5088],
          [0.0420, 0.9298, 0.3285],
          [0.3559, 0.1464, 0.4002]],
 
         [[0.0083, 0.8764, 0.2997],
          [0.8667, 0.9612, 0.8813],
          [0.3801, 0.7697, 0.0349],
          ...,
          [0.1634, 0.3213, 0.2645],
          [0.6406, 0.0988, 0.1234],
          [0.9210, 0.0606, 0.1889]],
 
         [[0.0727, 0.4719, 0.1820],
          [0.2892, 0.4999, 0.3812],
          [0.9037, 0.2588, 0.8806],
          ...,
          [0.0936, 0.0305, 0.8107],
          [0.1719, 0.6547, 0.0685],
          [0.0891, 0.5920, 0.5662]],
 
         ...,
 
         [[0.6459, 0.6471, 0.2752],
          [0.5385, 0.7588, 0.6862],
          [0.1368, 0.6568, 0.8956],
          ...,
          [0.2293, 0.3528, 0.4956],
          [0.8787, 0.2251, 0.1995],
          [0.5588, 0.7019, 0.8754]],
 
         [[0.7030, 0.1387, 0.8732],
          [0

- Zeros and Ones

In [14]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [15]:
ones = torch.ones(size = (3,4))
ones, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]),
 2)

- Creating a range and tensors like

In [16]:
zero_to_ten = torch.arange(0, 11)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# Syntax : arange(start, end, step)
evens = torch.arange(10, 51, 2)
evens

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
        46, 48, 50])

- Zeros like, Ones like

In [18]:
random_a = torch.rand(size = (3,3,4))
random_a

tensor([[[0.4427, 0.3098, 0.2902, 0.2034],
         [0.4495, 0.4092, 0.6739, 0.3484],
         [0.7812, 0.5964, 0.4498, 0.7590]],

        [[0.4371, 0.1881, 0.3724, 0.9596],
         [0.8302, 0.8150, 0.2899, 0.7480],
         [0.3380, 0.0313, 0.3393, 0.3589]],

        [[0.8522, 0.6304, 0.4099, 0.3398],
         [0.5049, 0.5882, 0.5415, 0.9398],
         [0.4996, 0.3574, 0.1211, 0.4100]]])

In [19]:
# Zeros like 
zeros_like = torch.zeros_like(random_a)
zeros_like

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
# Ones like 
ones_like = torch.ones_like(random_a)
ones_like

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

- Tensors Datatypes  

`torch.float16 or torch.half`, `torch.float32 or torch.float`, `torch.float64 or torch.double`

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor([3.0, 9.0],
                               dtype= torch.half)
float_16_tensor.dtype

torch.float16

- Getting information from tensors

In [23]:
# Three attribute (.shape, .dtype, .device)
some_tensor = torch.rand(3,4)
some_tensor.shape, some_tensor.dtype, some_tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

- Manipulating tensors

In [24]:
tensorA = torch.tensor([3, 5, 8])
tensorB = torch.tensor([7, 5, 2])

In [25]:
# Addition 
tensorA + tensorB

tensor([10, 10, 10])

In [26]:
tensorA + 10

tensor([13, 15, 18])

In [27]:
# Subtraction 
tensorA - tensorB

tensor([-4,  0,  6])

In [28]:
tensorB - 8

tensor([-1, -3, -6])

In [29]:
# Division 
tensorA / tensorB

tensor([0.4286, 1.0000, 4.0000])

In [30]:
tensorA // tensorB

tensor([0, 1, 4])

In [31]:
# Multiplication element wise 
tensorA * tensorB

tensor([21, 25, 16])

In [32]:
tensorA * 10

tensor([30, 50, 80])

- Matrix Multiplication 

In [33]:
tensorA.shape

torch.Size([3])

In [ ]:
tensorA @ tensorA # it is actually vector dot product

tensor(98)

In [47]:
%%time 
v = 0
for i in range(len(tensorA)):
    v += tensorA[i] * tensorA[i]

v

CPU times: total: 0 ns
Wall time: 571 μs


tensor(98)

In [ ]:
%%time 
torch.matmul(tensorA, tensorA) # more faster 
# because it uses the hardwares parallel computing 

CPU times: total: 0 ns
Wall time: 0 ns


tensor(98)

- Matrix multiplication error for size

In [52]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [53]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

- Not understood the below

In [64]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = tensor_A
output = linear(x)
x.shape, output, output.shape, tensor_A

(torch.Size([3, 2]),
 tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
         [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
         [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
        grad_fn=<AddmmBackward0>),
 torch.Size([3, 6]),
 tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]))

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = tensor_A
output = linear(x)
x.shape, output, output.shape

- Aggregation function

In [65]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
x.min(),x.max(), x.std(), x.sum()

RuntimeError: std and var only support floating point and complex dtypes

In [ ]:
x.std(), x.mean()
# Error: std, mean only support floating point 

RuntimeError: std and var only support floating point and complex dtypes

In [67]:
x.min(),x.max(), x.sum()

(tensor(0), tensor(90), tensor(450))

In [68]:
x.type(torch.float).std()

tensor(30.2765)

In [70]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

- Index of higest value 

In [74]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
tensor, [tensor.argmax(), 
         tensor.argmin()]

(tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]), [tensor(8), tensor(0)])

- Change tensor datatype

In [76]:
# Create a tensor and check its datatype
tensor_float32 = torch.arange(10., 100., 10.)
tensor_float32.dtype

torch.float32

In [78]:
tensor_float16 = tensor_float32.type(torch.float16)
tensor_float16.dtype

torch.float16

In [79]:
torch_intdefault = torch.tensor([1,2,3,4])
torch_intdefault.dtype

torch.int64

In [82]:
# int64 to float16 or half
tensor_float_half = torch_intdefault.type(torch.half)
tensor_float_half.dtype

torch.float16

- Reshaping,viewing, stacking, squeezing and unsqueezing

In [83]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [86]:
x_reshaped = x.reshape(1,7)
x_reshaped.shape

torch.Size([1, 7])

In [87]:
x = torch.arange(1,10)
x_reshaped = x.reshape(3,3)
x_reshaped.shape

torch.Size([3, 3])

- View  
changing the view changes the original tensor too.

In [88]:
y = torch.arange(1,10)
z = y.view(3,3)
y, z

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [100]:
# Stack tensors on top of each other
x = torch.tensor([1,2,3,4,5])
x_stacked = torch.stack([x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked.shape

torch.Size([2, 5])

In [99]:
# Stack tensors side by side
x = torch.tensor([1,2,3,4,5])
x_stacked = torch.stack([x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked.shape

torch.Size([5, 2])

| `dim` value | Shape       | What's happening         |
|-------------|-------------|--------------------------|
| `dim=0`     | `(2, 5)`    | Stack on top of each other (new outer axis) |
| `dim=1`     | `(5, 2)`    | Stack side by side (new inner axis)        |

In [101]:
x = torch.randn(1, 3, 1, 4, 1, 1)
x.shape

torch.Size([1, 3, 1, 4, 1, 1])

In [ ]:
x.squeeze().shape # removes all one dimension

torch.Size([3, 4])

In [ ]:
x.squeeze(2).shape # removes specific dimension of index 2

torch.Size([1, 3, 4, 1, 1])

In [ ]:
x.squeeze(2,4).shape # removes specific dimension of index 2,4

torch.Size([1, 3, 4, 1])

In [109]:
# Creating a tensor with a shape of (3, 4)
x = torch.randn(3, 4)
print("Original Tensor Shape:", x.shape)

unsqueezed_x = x.unsqueeze(dim=1)
print("Unsqueezed Tensor Shape:", unsqueezed_x.shape)

Original Tensor Shape: torch.Size([3, 4])
Unsqueezed Tensor Shape: torch.Size([3, 1, 4])


In [ ]:
# Creating a tensor with a shape of (3, 4)
x = torch.randn(3, 4)
print("Original Tensor Shape:", x.shape)

# Using unsqueeze to add a new dimension at index 2
unsqueezed_x = x.unsqueeze(2)
print("Unsqueezed Tensor Shape:", unsqueezed_x.shape)

Original Tensor Shape: torch.Size([3, 4])
Unsqueezed Tensor Shape: torch.Size([3, 4, 1])


In [114]:
# Create tensor with specific shape
x_original = torch.rand(size=(2, 5, 1, 4, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(4, 0, 1, 3, 2) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([2, 5, 1, 4, 3])
New shape: torch.Size([3, 2, 5, 4, 1])


PyTorch tensors & NumPy
- `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
- `tensor.numpy()` - PyTorch tensor -> NumPy array.

In [4]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1., 11.)
tensor = torch.from_numpy(array)
array, tensor, array.dtype, tensor.dtype

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64),
 dtype('float64'),
 torch.float64)

In [3]:
array = np.arange(1, 11)
tensor = torch.from_numpy(array)
array, tensor, array.dtype, tensor.dtype

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 dtype('int64'),
 torch.int64)

In [5]:
tensor = torch.arange(1., 6.)
numpy_array = tensor.numpy()
numpy_array, tensor, numpy_array.dtype, tensor.dtype

(array([1., 2., 3., 4., 5.], dtype=float32),
 tensor([1., 2., 3., 4., 5.]),
 dtype('float32'),
 torch.float32)

- Reproducibility (trying to take the random out of random)

Reproducibility means being able to get the same results every time you run your code — even if it involves randomness.

In [6]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B 

(tensor([[0.8528, 0.5276, 0.6332, 0.0574],
         [0.3161, 0.3725, 0.9957, 0.4663],
         [0.2812, 0.4072, 0.0341, 0.8001]]),
 tensor([[0.9060, 0.5611, 0.4392, 0.0141],
         [0.0947, 0.9548, 0.0317, 0.8876],
         [0.5747, 0.8568, 0.9228, 0.6013]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [26]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(seed = RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
[
[random_tensor_C, random_tensor_D],
random_tensor_C == random_tensor_D
]

[[tensor([[0.8823, 0.9150, 0.3829, 0.9593],
          [0.3904, 0.6009, 0.2566, 0.7936],
          [0.9408, 0.1332, 0.9346, 0.5936]]),
  tensor([[0.8823, 0.9150, 0.3829, 0.9593],
          [0.3904, 0.6009, 0.2566, 0.7936],
          [0.9408, 0.1332, 0.9346, 0.5936]])],
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]])]

- Exercise

In [28]:
# 2: Solution 
random_tensor_x = torch.rand(size = (7, 7))
random_tensor_x

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [29]:
# 3: Solution
random_tensor_y = torch.rand(size = (1, 7))
# (1x7) can't be multiply with (7x7)
# so I have to transpose (1x7) to (7x1)
random_tensor_x @ random_tensor_y.T

tensor([[1.2748],
        [1.1652],
        [1.0182],
        [1.7959],
        [1.6076],
        [1.8623],
        [0.7118]])

In [ ]:
# 4: solution 
