In [2]:
import torch
from torch import nn
import matplotlib.pyplot as plt

# Check Pytorch Version 
torch.__version__

# nn contains all of PyTorch's building blocks for neural networks 

'2.6.0+cpu'

---
- Tensors are the fundamental building block of machine learning 
- Their job is to represnt data in a numerical way
- we can represnt image into numbers too


#### Creating tensors

In [3]:
# Saclar tensor (Zero dimension, just a number)
scalar = torch.tensor(7)
scalar, scalar.dtype

(tensor(7), torch.int64)

In [4]:
scalar.ndim

0

- A vector is a single dimension tensor but can contain many numbers.

In [ ]:
vector = torch.tensor([7,7]) # count square brackets
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [ ]:
vector.shape # it shows the number of elements 

torch.Size([2])

In [8]:
v = torch.tensor([1,2,4,5])
v, v.ndim, v.shape

(tensor([1, 2, 4, 5]), 1, torch.Size([4]))

- MATRIX has two dimensions (did you count the number of square brackets on the outside of one side?).

In [9]:
Matrix = torch.tensor([[1,2],
                       [3,4]])

In [10]:
Matrix, Matrix.ndim, Matrix.shape

(tensor([[1, 2],
         [3, 4]]),
 2,
 torch.Size([2, 2]))

- Tensors are 3D array

In [ ]:
Tensor = torch.tensor([[[1,2,3],
                        [3,4,5]],
                        [[1,2,4],
                         [3,4,5]]])
Tensor, Tensor.ndim, Tensor.shape
# 2 ta 2x3 Matrix 

(tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[1, 2, 4],
          [3, 4, 5]]]),
 3,
 torch.Size([2, 2, 3]))

- Random tensors

In [12]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3798, 0.7187, 0.2344, 0.0117],
         [0.1894, 0.9834, 0.5239, 0.6645],
         [0.7761, 0.4141, 0.7857, 0.2326]]),
 torch.float32)

- The flexibility of torch.rand() is that we can adjust the size to be whatever we want.

- For example, say you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

In [17]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor, random_image_size_tensor.ndim, random_image_size_tensor.shape

(tensor([[[7.6528e-01, 4.3714e-01, 4.4143e-01],
          [6.6607e-01, 1.9373e-01, 9.5005e-01],
          [2.5403e-01, 8.0087e-01, 6.8590e-01],
          ...,
          [5.1869e-01, 5.8176e-01, 1.9605e-01],
          [4.3058e-01, 3.4157e-01, 3.1647e-01],
          [1.9750e-01, 1.4621e-02, 3.1342e-01]],
 
         [[3.7648e-02, 2.8228e-01, 4.6823e-01],
          [8.9236e-01, 4.0516e-01, 7.2546e-01],
          [6.7174e-01, 9.0021e-01, 6.0603e-01],
          ...,
          [3.2332e-01, 3.0071e-01, 8.7744e-01],
          [7.3147e-04, 1.0487e-01, 4.6993e-01],
          [2.0207e-01, 1.6551e-01, 4.8704e-01]],
 
         [[3.1484e-01, 7.7662e-01, 3.8400e-01],
          [4.5506e-01, 7.5635e-01, 3.2506e-01],
          [1.2347e-01, 7.2540e-01, 2.8359e-01],
          ...,
          [2.7458e-01, 2.0799e-01, 4.0259e-01],
          [6.7754e-01, 2.3043e-02, 8.2361e-01],
          [5.7597e-01, 3.3896e-01, 7.6366e-03]],
 
         ...,
 
         [[3.2899e-01, 8.8925e-01, 2.1544e-01],
          [9.6277e

- Zeros and Ones

In [14]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [16]:
ones = torch.ones(size = (3,4))
ones, ones.shape, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]),
 2)

- Creating a range and tensors like

In [20]:
zero_to_ten = torch.arange(0, 11)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Syntax : arange(start, end, step)
evens = torch.arange(10, 51, 2)
evens

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
        46, 48, 50])

- Zeros like, Ones like

In [23]:
random_a = torch.rand(size = (3,3,4))
random_a

tensor([[[0.2144, 0.3971, 0.7090, 0.6540],
         [0.2180, 0.6367, 0.7886, 0.3702],
         [0.4598, 0.4719, 0.5605, 0.0785]],

        [[0.8398, 0.6756, 0.1626, 0.5524],
         [0.7390, 0.8392, 0.9147, 0.9749],
         [0.9217, 0.0020, 0.7993, 0.4391]],

        [[0.8893, 0.5015, 0.3933, 0.1623],
         [0.1217, 0.3193, 0.7268, 0.6102],
         [0.0226, 0.6642, 0.2615, 0.1922]]])

In [25]:
# Zeros like 
zeros_like = torch.zeros_like(random_a)
zeros_like

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [27]:
# Ones like 
ones_like = torch.ones_like(random_a)
ones_like

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

- Tensors Datatypes  

`torch.float16 or torch.half`, `torch.float32 or torch.float`, `torch.float64 or torch.double`

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [30]:
float_16_tensor = torch.tensor([3.0, 9.0],
                               dtype= torch.half)
float_16_tensor.dtype

torch.float16

- Getting information from tensors

In [31]:
# Three attribute (.shape, .dtype, .device)
some_tensor = torch.rand(3,4)
some_tensor.shape, some_tensor.dtype, some_tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

- Manipulating tensors

In [36]:
tensorA = torch.tensor([3, 5, 8])
tensorB = torch.tensor([7, 5, 2])

In [37]:
# Addition 
tensorA + tensorB

tensor([10, 10, 10])

In [38]:
tensorA + 10

tensor([13, 15, 18])

In [39]:
# Subtraction 
tensorA - tensorB

tensor([-4,  0,  6])

In [40]:
tensorB - 8

tensor([-1, -3, -6])

In [ ]:
# Division 
tensorA / tensorB

tensor([0.4286, 1.0000, 4.0000])

In [42]:
tensorA // tensorB

tensor([0, 1, 4])

In [43]:
# Multiplication element wise 
tensorA * tensorB

tensor([21, 25, 16])

In [44]:
tensorA * 10

tensor([30, 50, 80])

- Matrix Multiplication 