**1. Getting ready data**

1. Getting ready data
2. Building a model
3. Fitting the model to data(training)
4. Making predictions and evaluating model(inference)
5. Saving and loading a model
6. Putting all together

In [32]:
import torch
from torch import nn
import matplotlib.pyplot as plt

torch.__version__

'2.5.1'

In [33]:
weight = 0.7
bias = 0.3

start = 0
end = 1
step = .02

X = torch.arange(start, end, step)
y = weight * X+ bias

X[:3], y[:3]

(tensor([0.0000, 0.0200, 0.0400]), tensor([0.3000, 0.3140, 0.3280]))

In [34]:
X = torch.unsqueeze(X,dim=1)
y = torch.unsqueeze(y,dim=1)
X[:3], y[:3]

(tensor([[0.0000],
         [0.0200],
         [0.0400]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280]]))

In [35]:
len(X), len(y)

(50, 50)

In [36]:
train_split = len(X) * .8
train_split, type(train_split)

(40.0, float)

In [37]:
train_split = int(train_split)

In [40]:
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]
len(X_train), len(X_test), len(y_train), len(y_test)

(40, 10, 40, 10)

- Let's create a function to visualize it