- It will give random values

In [6]:
import torch
randn = torch.randn(1, dtype = torch.float)
randn

tensor([1.4493])

- Using manual seed (Remains always )

In [12]:
torch.manual_seed(42)
randn = torch.randn(1, dtype=float)
randn

tensor([0.3367], dtype=torch.float64)

In [16]:
torch.manual_seed(42)
rand = torch.rand(1,3)
rand

tensor([[0.8823, 0.9150, 0.3829]])