#### **Introduction to Tensors**
- PyTorch Version & CPU availability

In [7]:
import torch 
print(torch.__version__)
print(torch.cuda.is_available())  # Should print False (since it's CPU only)

2.5.1
False


- #### **Creating Tensor**

---

- Scaler (Normal value)

In [8]:
# Scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [10]:
# dimension of scaler
scaler.ndim

0

In [11]:
# tensor() takes 1 positional argument but 2 were given
scaler = torch.tensor(7,8)
scaler

TypeError: tensor() takes 1 positional argument but 2 were given

In [12]:
# dimension of scaler
scaler.ndim

0

In [13]:
# Get tensor back as Python int
scaler.item()

7

---

- Vector (1D array)

In [19]:
# Vector 
vector = torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [20]:
vector.ndim

1

In [21]:
vector.shape 

torch.Size([3])

In [22]:
vector = torch.tensor([[1,2,3]])
vector, vector.ndim, vector.shape 
# dimension - 2 & size/order 1x3
# it is not actually a vector, it's a matrix

(tensor([[1, 2, 3]]), 2, torch.Size([1, 3]))

---
- MATRIX (2D array)

In [24]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,6]])
MATRIX

tensor([[7, 8],
        [9, 6]])

In [25]:
MATRIX.ndim

2

In [26]:
MATRIX.shape

torch.Size([2, 2])

In [27]:
MATRIX[1]

tensor([9, 6])

---
- Tensor (3D array)

In [28]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [29]:
TENSOR.ndim

3

In [31]:
TENSOR.shape # 1 ta 3x3 Matrix ache

torch.Size([1, 3, 3])

---
- **Random tensors**

Why random tensors?

Random tensors are important because the way neural network learn is that they start with tensors full of random numbers and then adjust  those random numbers to better represent the data.

`Strat with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [32]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7999, 0.3040, 0.5946, 0.3491],
        [0.4298, 0.6365, 0.3410, 0.9006],
        [0.2226, 0.6788, 0.1841, 0.0125]])

In [33]:
random_tensor.ndim

2

In [34]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3,3) # torch.rand(size=(3,3)) -> same

tensor([[0.2952, 0.9759, 0.7994],
        [0.5230, 0.5841, 0.7295],
        [0.2747, 0.0066, 0.0583]])

In [36]:
torch.rand(1,3,3), torch.rand(1,3,3).shape, torch.rand(1,3,3).ndim

(tensor([[[0.7741, 0.6852, 0.6592],
          [0.2158, 0.7583, 0.0271],
          [0.7040, 0.2520, 0.6472]]]),
 torch.Size([1, 3, 3]),
 3)

- Zeros and Ones

In [38]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
zeros = torch.zeros(1,3,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [40]:
zeros = torch.zeros(size=(3,4)) * torch.rand(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

---
- Creating a range of tensors and tensors like
`torch.arange(start, end, update)`

In [45]:
# Use torch.range()
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
# Even numbers
torch.arange(2, 20, 2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
# Odd numbers 
torch.arange(1, 20, 2)

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [48]:
one_to_ten = torch.arange(1, 11)
one_to_ten 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

- Arange to Matrix

In [53]:
# using view
tensor = torch.arange(1, 10).view(3, 3)
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
# using reshape
tensor = torch.arange(1, 10).reshape(3,3)
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

---
- **Tensor datatypes**

**Note:** Tensor datatypes is one of the 3 big errors I'll run into with PyTorch & DeepLearning  
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the rith device 

In [ ]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0])
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device='cpu', # what device is your tensor on 
                               requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
x_16_str = '16'
y_16_int = int(x_16_str)
y_16_int , type(y_16_int)

(16, int)

- **Tensor Attribute**

In [2]:
import torch

In [3]:
int_32_tensor = torch.tensor([3, 4, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 9], dtype=torch.int32)

In [4]:
float_64_tensor = torch.tensor([3.0, 4.0, 9.0], dtype=torch.float64)
float_64_tensor

tensor([3., 4., 9.], dtype=torch.float64)

In [5]:
int_32_tensor * float_64_tensor

tensor([ 9., 16., 81.], dtype=torch.float64)

---
**Getting information from tensors** (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get a shape from a tensor, can use `tensor.shape`
3. Tensors not on the rith device - to get device from a tensor, can use `tensor.device`

In [6]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1334, 0.5432, 0.8977, 0.8110],
        [0.8319, 0.7227, 0.6394, 0.0681],
        [0.1639, 0.7480, 0.1555, 0.7427]])

In [7]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1334, 0.5432, 0.8977, 0.8110],
        [0.8319, 0.7227, 0.6394, 0.0681],
        [0.1639, 0.7480, 0.1555, 0.7427]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


---
**Manipulating Tensors** (tensor operations)  
Tensor operations include:
* Addition
* Subtration
* Multiplication (element-wise)
* Division
* Matrix multiplication 

In [11]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [12]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [13]:
tensor - 10

tensor([-9, -8, -7])

In [14]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [15]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

---
**Matrix multiplication** (dot product)

In [18]:
# Element wise multiplication
print(tensor)
print(tensor * tensor)

tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor) # it is a vector dot product.
# Explanation 
# tensor = [1, 2, 3] which is 1x3 Matrix 
# we are doing --> tensor * tensor

tensor(14)

In [20]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value 

CPU times: total: 0 ns
Wall time: 14.2 ms


tensor(14)

In [21]:
%%time 
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

---
#### **Matirx multiplication** rules
* Column of first matrix must be equal to row of first matrix (Inner dimensions must match)
- `(2x3)` @ `(3x2)` will work
- `(2x3)` @ `(2x3)` won't work
* Resulting matrix has the shape of the **outer dimensions**
- `(2x3)` @ `(3x2)` -> `(2x2)` 

In [22]:
torch.matmul(torch.rand(3,4),torch.rand(4,5))

tensor([[0.8824, 1.0467, 1.2877, 1.0658, 1.1210],
        [1.1464, 1.6138, 1.9762, 1.6080, 1.4860],
        [0.8588, 0.9103, 0.9717, 0.9994, 0.9310]])

---
- One of the most common errors in deep learning: shape errors

In [24]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [25]:
tensor_a = torch.rand(3,2)
tensor_b = torch.rand(3,2)
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [26]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

---
#### Transpose matrix
- To fix our tensor shape issues, we can manipulate the shape of one of our tensor using `transpose.`
- A `transpose` switches the axes or dimensions of a given tensor.

In [27]:
tensor_b.T, tensor_b

(tensor([[0.1176, 0.0554, 0.2934],
         [0.9690, 0.4066, 0.7979]]),
 tensor([[0.1176, 0.9690],
         [0.0554, 0.4066],
         [0.2934, 0.7979]]))

In [28]:
tensor_b.shape, tensor_b.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [33]:
torch.matmul(tensor_a, tensor_b.T).shape

torch.Size([3, 3])

#### **Tensor aggregation**
- Finding the min, max, mean, sum, etc

In [57]:
import torch

In [65]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype # int64 which is a long data type

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [61]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [62]:
# Find the max 
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the average
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [66]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [67]:
x.type(torch.float32).mean()

tensor(45.)

In [69]:
# Find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

#### **Finding the index of min and max**

In [71]:
# Find the index of min and max using argmin(), argmax()
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

#### **Reshaping, viewing,stacking, squeezing, unsqueezing and permuting**  
- Reshaping - reshapes an input to a defined shape
- View - return a view of an input tensor of certain shape but keep the same memory
- Stacking - combine multiple tensor on top of other (vstack) or side by side (hstack)
- Squeeze - remove all `1` dimensions from a tensor
- Unsqueezee - add a `1` dimension to a target tensor.
- Permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [9]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [11]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [12]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [13]:
x_reshaped = x.reshape(2, 9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [14]:
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [16]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [17]:
x_viewed = x.view(1,9)
x_viewed, x_viewed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

- Changing x_viewed changes x (because a view of a tensor shares the same memory as the original input)

In [18]:
x_viewed[:,0] = 5
x_viewed, x # Same output because sharing same memory

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [19]:
# Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
# Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [21]:
# Stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [22]:
import torch

In [40]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size(), x.shape, x.ndim, x

(torch.Size([2, 1, 2, 1, 2]),
 torch.Size([2, 1, 2, 1, 2]),
 5,
 tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]))

In [42]:
y = torch.squeeze(x)
y.size(), y

(torch.Size([2, 2, 2]),
 tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [43]:
y = torch.squeeze(x, 0)
y.size(), y

(torch.Size([2, 1, 2, 1, 2]),
 tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]))

In [44]:
y = torch.squeeze(x, 1)
y.size(), y

(torch.Size([2, 2, 1, 2]),
 tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]))

In [46]:
y = torch.squeeze(x, 3)
y.size(), y

(torch.Size([2, 1, 2, 2]),
 tensor([[[[0., 0.],
           [0., 0.]]],
 
 
         [[[0., 0.],
           [0., 0.]]]]))

In [35]:
# torch.squeeze() - remove all single dimensions from a target tensor
x_reshaped = torch.reshape(x_reshaped,(1,9))
# x_reshaped = torch.reshape(x_reshaped,(-1,))
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [36]:
x_reshaped.shape

torch.Size([1, 9])

In [38]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
x_reshaped.squeeze().shape

torch.Size([9])

In [47]:
x_squeezed = x_reshaped.squeeze()

In [48]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [54]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [53]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 2)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [2]:
import torch

In [3]:
# torch.permute - rearange the dimensions of a target tensor in a specified order 
x = torch.randn(2, 3, 5)
x.shape, x

(torch.Size([2, 3, 5]),
 tensor([[[-1.1618e-01, -9.2363e-01,  1.3316e+00,  4.6225e-01, -1.4207e-03],
          [-1.0492e+00, -3.5420e-01, -7.5696e-01,  4.7893e-01,  3.7291e-01],
          [ 5.0280e-01, -3.8928e-01,  2.2191e-01,  2.9747e-01,  1.2283e+00]],
 
         [[-1.0911e-01, -8.7206e-01, -1.1490e+00,  7.2826e-01,  1.7580e+00],
          [ 2.1836e-01,  9.0403e-01,  6.2544e-01, -1.8243e+00, -1.0672e+00],
          [-1.2142e-01,  1.0159e+00,  2.5746e-01,  9.6864e-01, -7.0644e-02]]]))

In [5]:
x_permuted = x.permute((2, 0, 1))
x_permuted, x_permuted.shape

(tensor([[[-1.1618e-01, -1.0492e+00,  5.0280e-01],
          [-1.0911e-01,  2.1836e-01, -1.2142e-01]],
 
         [[-9.2363e-01, -3.5420e-01, -3.8928e-01],
          [-8.7206e-01,  9.0403e-01,  1.0159e+00]],
 
         [[ 1.3316e+00, -7.5696e-01,  2.2191e-01],
          [-1.1490e+00,  6.2544e-01,  2.5746e-01]],
 
         [[ 4.6225e-01,  4.7893e-01,  2.9747e-01],
          [ 7.2826e-01, -1.8243e+00,  9.6864e-01]],
 
         [[-1.4207e-03,  3.7291e-01,  1.2283e+00],
          [ 1.7580e+00, -1.0672e+00, -7.0644e-02]]]),
 torch.Size([5, 2, 3]))

In [6]:
x_original = torch.rand(size=(224, 224, 3)) # [Height, width, color_channels]
                            #  0    1   2 
# permute the original tensor to rearange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [8]:
x_original[0, 0, 0] = 8754

In [9]:
x_permuted[0, 0,0] # it's like view

tensor(8754.)

#### **Indexing (selecting data from tensors)**
Indexing with PyTorch is similar to indexing with NumPy.

In [11]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape
# this One 3x3 matirx

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [12]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
x[0][0] # x[0, 0]

tensor([1, 2, 3])

In [14]:
x[0,0,0]

tensor(1)

In [16]:
x[0][2][2]

tensor(9)

- Slicing 

In [17]:
x[:, :, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
x[:, 0]

tensor([[1, 2, 3]])

---
**PyTorch and NumPy**

Numpy is a popular scientific Python numerical computing library.  
And because of this, PyTorch has functionality to interect with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.tensor.numpy`

In [22]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# default numpy datatype float64
array.dtype , tensor.dtype # this data type comes from numpy's default datatype

(dtype('float64'), torch.float64)

In [ ]:
# tensor's default datatype float32
torch.tensor([1.,2.,3.,4.]).dtype

torch.float32

In [30]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
[array, tensor, array.dtype, tensor.dtype]

[array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 torch.float32]

In [ ]:
# change the value of array, what will this do to `tensor`?
# it do not affect tensor
array = array + 1
array

array([3., 4., 5., 6., 7., 8., 9.])

In [33]:
[array, tensor]

[array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.])]

In [34]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [35]:
tensor = tensor + 1
[tensor, numpy_tensor]

[tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)]

---
**Reproducibility (Trying to take random out of random)**

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data-> again -> again -> again....`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

Essentially what the random seed does is 'flavour' the randomness

In [36]:
torch.rand(3,3)

tensor([[0.6003, 0.3180, 0.3193],
        [0.4168, 0.7708, 0.5995],
        [0.9634, 0.5932, 0.9998]])

In [37]:
# Create two random tensors

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)
[random_tensor_a, random_tensor_b, random_tensor_a == random_tensor_b]

[tensor([[0.3119, 0.9688, 0.5609, 0.5953],
         [0.2240, 0.6287, 0.8049, 0.8876],
         [0.6150, 0.1129, 0.2823, 0.5864]]),
 tensor([[0.4791, 0.2322, 0.2624, 0.7758],
         [0.6995, 0.2386, 0.0668, 0.2412],
         [0.0956, 0.5309, 0.5778, 0.0927]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]])]

In [39]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
[random_tensor_c, random_tensor_d, random_tensor_c == random_tensor_d]


[tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]])]

- Permute 

In [2]:
import torch

In [4]:
# Create tensor with specific shape
x_original = torch.rand(size=(3, 5,4))

# Permute the original tensor to rearange the axis order
x_permuted = x_original.permute(2, 0, 1)

x_original.shape, x_permuted.shape

(torch.Size([3, 5, 4]), torch.Size([4, 3, 5]))

In [5]:
# change shape as you want by index
x_permuted = x_original.permute(1, 2, 0)
x_original.shape, x_permuted.shape

(torch.Size([3, 5, 4]), torch.Size([5, 4, 3]))

In [6]:
x = torch.rand(size=(3, 4))
x_permute = x.permute(1, 0)
x, x_permute

(tensor([[0.8518, 0.8664, 0.9775, 0.4039],
         [0.8985, 0.7936, 0.9984, 0.7075],
         [0.4991, 0.6781, 0.4775, 0.4361]]),
 tensor([[0.8518, 0.8985, 0.4991],
         [0.8664, 0.7936, 0.6781],
         [0.9775, 0.9984, 0.4775],
         [0.4039, 0.7075, 0.4361]]))

**PyTorch tensor and NumPy**

In [9]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
# numpy array to tensor
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [10]:
array = np.arange(1, 10).reshape(3,3)
# numpy array to tensor 
tensor = torch.from_numpy(array)
array, tensor

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]], dtype=torch.int32))

In [12]:
tensor = torch.arange(1, 10).reshape(3, 3)
# tensor to array
array = tensor.numpy()
array, tensor

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int64),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [14]:
tensor = torch.ones(9).reshape(3,3)
# tensor to array 
array = tensor.numpy()
array, tensor

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

---
- Numpy array to tensor and tensor to numpy array

In [16]:
array = np.arange(1, 4)

tensor = torch.from_numpy(array)

array, tensor

(array([1, 2, 3]), tensor([1, 2, 3], dtype=torch.int32))

In [17]:
tensor = torch.arange(1, 4)

array = tensor.numpy()

array, tensor

(array([1, 2, 3], dtype=int64), tensor([1, 2, 3]))

- Reproducibility

In [18]:
import torch

random_tensor_A = torch.rand(2,2)
random_tensor_B = torch.rand(2,2)

[random_tensor_A, random_tensor_B], [random_tensor_A == random_tensor_B]

([tensor([[0.0116, 0.1456],
          [0.5086, 0.8709]]),
  tensor([[0.6194, 0.1671],
          [0.9137, 0.8038]])],
 [tensor([[False, False],
          [False, False]])])

In [20]:
import torch
import random

# Set the random seed
RANDOM_SEED = 8
torch.manual_seed(seed = RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

[random_tensor_A, random_tensor_B], [random_tensor_A == random_tensor_B]

([tensor([[0.5979, 0.8453, 0.9464, 0.2965],
          [0.5138, 0.6443, 0.8991, 0.0141],
          [0.5785, 0.1218, 0.9181, 0.6805]]),
  tensor([[0.5979, 0.8453, 0.9464, 0.2965],
          [0.5138, 0.6443, 0.8991, 0.0141],
          [0.5785, 0.1218, 0.9181, 0.6805]])],
 [tensor([[True, True, True, True],
          [True, True, True, True],
          [True, True, True, True]])])