### **Tensors**
- Tensors are a specialized data structure that are very similar to arrays and matrices.

In [1]:
import torch
import numpy as np

- Initializing a Tensor

In [3]:
data = [[1, 2],[2, 3]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [2, 3]])

- Creating from NumPy array

In [4]:
np_array = np.array(data)
x_np_array = torch.from_numpy(np_array)

In [5]:
x_np_array

tensor([[1, 2],
        [2, 3]])

- Creating from another tensor

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [ ]:
x_ones = torch.ones_like(x_data)# retains the properties of x_data
print(f"Ones Tensor:\n{x_ones}\n")

Ones Tensor:
tensor([[1, 1],
        [1, 1]])



In [9]:
x_rand = torch.rand_like(x_data, dtype=torch.float)# overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.1411, 0.6876],
        [0.9117, 0.0670]]) 



---

**With random or constant values**  

- `shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [12]:
shape = (2,3,) # 2x3 Order
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n{rand_tensor} \n")
print(f"Ones Tensor: \n{ones_tensor} \n")
print(f"Zeros Tensor: \n{zeros_tensor}")
print(f"Dimension: {rand_tensor.ndim}")

Random Tensor: 
tensor([[0.8645, 0.0971, 0.4163],
        [0.5004, 0.1765, 0.1737]]) 

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Dimension: 2


--- 

**Tensor Attributes**

- Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [13]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


---
**Tensor Operations**
- Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described

In [15]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")
else:
  print("You don't have a GPU")

You don't have a GPU


In [17]:
tensor = torch.ones(4, 4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# tensor[start:end, start:end]
# tensor[row, column]
tensor[1:3, 1:] 

tensor([[1., 1., 1.],
        [1., 1., 1.]])

You have to complete this: 
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label