**Introduction to tensors**

In [3]:
# PyTorch version and CPU availability
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1
False


In [2]:
# PyTorch version and CPU availibility
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1
False


In [4]:
# PyTorch Version and availablity
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1
False


- **Creating Tensor**

In [5]:
# Scaler (Normal integer value with no dimension)
scaler = torch.tensor(7)
[scaler, scaler.shape, scaler.ndim]

[tensor(7), torch.Size([]), 0]

In [6]:
# I can't put multiple value in scaler
sclaer = torch.tensor(10, 20)
[scaler, sclaer.shape, sclaer.ndim]

TypeError: tensor() takes 1 positional argument but 2 were given

In [7]:
# Creating a scaler tensor
sclaer = torch.tensor(10)
[scaler, scaler.shape, scaler.ndim]

[tensor(7), torch.Size([]), 0]

In [8]:
# creating a scaler tensor
scaler = torch.tensor(9)
[scaler, scaler.shape, sclaer.ndim]

[tensor(9), torch.Size([]), 0]

In [9]:
# Get tensor back as Python int
scaler.item()

9

- Vector (1D array)

In [10]:
vector = torch.tensor([1,2,3,4])
[vector, vector.shape, vector.ndim]

[tensor([1, 2, 3, 4]), torch.Size([4]), 1]

In [11]:
# Creating vector 1D array
# actually it's a 1D array
vector = torch.tensor([4, 5, 7])
[vector, vector.shape, vector.ndim]

[tensor([4, 5, 7]), torch.Size([3]), 1]

In [12]:
# Vector (1D array)
vector = torch.tensor([4, 5, 6])
[vector, vector.shape, vector.ndim]

[tensor([4, 5, 6]), torch.Size([3]), 1]

In [13]:
[vector[0], vector[1], vector[2]]

[tensor(4), tensor(5), tensor(6)]

In [ ]:
vector[1, 0] # In this way that is not possible

IndexError: too many indices for tensor of dimension 1

In [ ]:
vector[[1, 0]] # But in this way its possible

tensor([5, 4])

In [16]:
vector[[1, 1]]

tensor([5, 5])

- Matrix (3D array)

In [3]:
import torch

In [4]:
# MATRIX 
MATRIX = torch.tensor([[1, 2, 3],
                       [2, 4, 5],
                       [2, 5, 6]])
[MATRIX, MATRIX.shape, MATRIX.ndim]

[tensor([[1, 2, 3],
         [2, 4, 5],
         [2, 5, 6]]),
 torch.Size([3, 3]),
 2]

In [9]:
# Accessing index
MATRIX[[1, 2]], MATRIX[[2, 1]]

(tensor([[2, 4, 5],
         [2, 5, 6]]),
 tensor([[2, 5, 6],
         [2, 4, 5]]))

In [10]:
[MATRIX[0], MATRIX[1], MATRIX[2]]

[tensor([1, 2, 3]), tensor([2, 4, 5]), tensor([2, 5, 6])]

In [11]:
MATRIX[::]

tensor([[1, 2, 3],
        [2, 4, 5],
        [2, 5, 6]])

In [14]:
MATRIX[1::] # 1 Skipped (First row skipped)

tensor([[2, 4, 5],
        [2, 5, 6]])

In [16]:
MATRIX[2::] # 0,1 row skipped

tensor([[2, 5, 6]])

**Slicing MATRIX**  

`MATRIX[::, ::]` -> `MATRIX[row, column]`

In [18]:
MATRIX[::,::] # all row column

tensor([[1, 2, 3],
        [2, 4, 5],
        [2, 5, 6]])

In [19]:
MATRIX[1::,::]

tensor([[2, 4, 5],
        [2, 5, 6]])

In [20]:
MATRIX[1::,1::]

tensor([[4, 5],
        [5, 6]])

In [21]:
MATRIX[:2:,:2:]

tensor([[1, 2],
        [2, 4]])

* Tensor (3D/4D.... array)

In [28]:
TENSOR = torch.tensor([
    [[1,2,1],
    [1,2,0],
    [1,2,5]],
    [[1,2,9],
     [1,2,0],
     [1,2,9]        
    ]])
[TENSOR, TENSOR.shape, TENSOR.ndim]
# 2 Ta 3x3 Matrix

[tensor([[[1, 2, 1],
          [1, 2, 0],
          [1, 2, 5]],
 
         [[1, 2, 9],
          [1, 2, 0],
          [1, 2, 9]]]),
 torch.Size([2, 3, 3]),
 3]

- Index access

In [29]:
TENSOR[0], TENSOR[1]

(tensor([[1, 2, 1],
         [1, 2, 0],
         [1, 2, 5]]),
 tensor([[1, 2, 9],
         [1, 2, 0],
         [1, 2, 9]]))

In [30]:
TENSOR[[1, 0]]

tensor([[[1, 2, 9],
         [1, 2, 0],
         [1, 2, 9]],

        [[1, 2, 1],
         [1, 2, 0],
         [1, 2, 5]]])

- Slicing `3D` tensor 

`tensor[::,::,::]` -> `tensor[index, row,column]`

In [32]:
TENSOR[0:1:]

tensor([[[1, 2, 1],
         [1, 2, 0],
         [1, 2, 5]]])

In [33]:
TENSOR[1::]

tensor([[[1, 2, 9],
         [1, 2, 0],
         [1, 2, 9]]])

In [34]:
TENSOR[::,::]

tensor([[[1, 2, 1],
         [1, 2, 0],
         [1, 2, 5]],

        [[1, 2, 9],
         [1, 2, 0],
         [1, 2, 9]]])

In [36]:
# Generating a 3D tensor with 5 elements
new_tensor = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],
    
    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]],
    
    [[28, 29, 30],
     [31, 32, 33],
     [34, 35, 36]],
    
    [[37, 38, 39],
     [40, 41, 42],
     [43, 44, 45]]
])
# [new_tensor, new_tensor.shape, new_tensor.ndim]

In [39]:
new_tensor[1::,1::,::]

tensor([[[13, 14, 15],
         [16, 17, 18]],

        [[22, 23, 24],
         [25, 26, 27]],

        [[31, 32, 33],
         [34, 35, 36]],

        [[40, 41, 42],
         [43, 44, 45]]])

In [40]:
new_tensor[2:3:,1::, 1::]

tensor([[[23, 24],
         [26, 27]]])

**What I learned till now?**
- PyTorch version & availiblity
- Creating Tensors(Scaler(0D), Vector(1D), Matrix(2D), Tensor(3D/nD))
- Slicing and Accessing index

---
**Random tensors**

In [41]:
random_tensor = torch.rand(3,4)
[random_tensor, random_tensor.shape, random_tensor.ndim]

[tensor([[0.4845, 0.3423, 0.7272, 0.9581],
         [0.0781, 0.0894, 0.6845, 0.0863],
         [0.9704, 0.5304, 0.5854, 0.5688]]),
 torch.Size([3, 4]),
 2]

In [42]:
random_tensor = torch.rand(3,4)
[random_tensor, random_tensor.shape, random_tensor.ndim]

[tensor([[0.3029, 0.4290, 0.0097, 0.2805],
         [0.7767, 0.4642, 0.0180, 0.4894],
         [0.9412, 0.8822, 0.9604, 0.0067]]),
 torch.Size([3, 4]),
 2]

In [43]:
random_tensor = torch.rand(size=(3,3))
random_tensor

tensor([[0.3814, 0.1543, 0.7361],
        [0.5727, 0.9032, 0.0162],
        [0.4395, 0.1728, 0.2843]])

In [44]:
[torch.rand(1,3,3), torch.rand(1, 3, 3).shape, torch.rand(1, 3, 3).ndim]

[tensor([[[0.7351, 0.7082, 0.1702],
          [0.0763, 0.5299, 0.5821],
          [0.7156, 0.5830, 0.5347]]]),
 torch.Size([1, 3, 3]),
 3]

- Zeros & Ones

In [ ]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [49]:
zeros = torch.zeros(1, 3, 4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [50]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [51]:
ones = torch.ones(size=(1,2,3))
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [52]:
ones.dtype

torch.float32

In [53]:
torch.arange(1, 11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
torch.zeros_like(torch.arange(1, 11))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
torch.zeros_like(torch.arange(1,10).reshape(3,3))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [57]:
torch.ones_like(torch.arange(1,11))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

- Arange to matrix

In [58]:
torch.arange(1,10).reshape(1,3,3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

- Tensor datatype

In [59]:
# default tensor datatype
tensor = torch.arange(1, 10).reshape(3, 3)
tensor.dtype

torch.int64

In [60]:
tensor = torch.arange(1., 10.).reshape(3, 3)
tensor.dtype

torch.float32

In [61]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0],
                               dtype=None,
                               device='cpu',
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 4., 5.])

- Type Conversion 

In [62]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [64]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [66]:
int_32_tensor = float_16_tensor.type(torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

- Tensor attribute `(tensor.dtype, tensor.shape, tensor.device)`

In [68]:
tensor = torch.rand(3,3)
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Shape of tensor: {tensor.shape}')
print(f'Device tensor is on: {tensor.device}')

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 3])
Device tensor is on: cpu


- Manipulating Tensors (tensor operations)  


Addition, Subtraction, Multiplication(element-wise), Division, Matrix multiplication

In [69]:
# tensor addition
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])
[tensor_a + tensor_b, tensor_a + 10]

[tensor([5, 7, 9]), tensor([11, 12, 13])]

In [70]:
# tensor subtraction
[tensor_b - tensor_a, tensor_b - 10]

[tensor([3, 3, 3]), tensor([-6, -5, -4])]

In [71]:
# Multiply element wise
tensor_a * 5

tensor([ 5, 10, 15])

In [73]:
# Division
tensor_a / 2

tensor([0.5000, 1.0000, 1.5000])

- Matrix Multiplication 

In [ ]:
# Matrix multiplicaiton 
tensor_a = torch.arange(5,15).reshape(3,3)
tensor_b = torch.arange()

tensor([ 4, 10, 18])