**NN Module of PyTorch**

* Building a model with One Linear layer

In [ ]:
# X_train  →  Linear layer (with 1 unit)  →  Sigmoid activation  →  Output

In [ ]:
import torch
from torch import nn

# Define a custom model class that inherits from PyTorch's base nn.Module
class Model_V1(nn.Module):
    def __init__(self, in_features):
        super().__init__()  # Initialize parent class (nn.Module)

        # Define a linear (fully connected) layer
        # Takes 'in_features' inputs and outputs a single value
        self.linear = nn.Linear(in_features=in_features,
                                out_features=1)

        # Define a sigmoid activation function
        # Note: Should be nn.Sigmoid() (capital S), not nn.sigmoid()
        self.sigmoid = nn.Sigmoid()

    def forward(self, X):
        # Pass input X through the linear layer (apply weights & bias)
        z = self.linear(X)

        # Apply sigmoid activation to squash output between 0 and 1
        y_pred = self.sigmoid(z)

        # Return the predicted value
        return y_pred


- `self.linear`, `self.sigmoid` 
They’re defined in `__init__` so that the same layers/operations (`self.linear`, `self.sigmoid`) can be reused inside `forward` during every call.


In [ ]:
# Create a dummy dataset
X_train = torch.rand(10, 5)

# Create model
model = Model_V1(X_train.shape[1])

# Call the forward pass
# model.foward(X) -> this not recommended
model(X_train) # Recommended by PyTorch

tensor([[0.3905],
        [0.4013],
        [0.3926],
        [0.4168],
        [0.4572],
        [0.4094],
        [0.4361],
        [0.4107],
        [0.4612],
        [0.3942]], grad_fn=<SigmoidBackward0>)

In [8]:
# Print weights and bias
print(f"{model.linear.weight}")

Parameter containing:
tensor([[-0.1459, -0.1894, -0.3744, -0.0159,  0.3304]], requires_grad=True)


In [7]:
print(f"{model.linear.bias}")

Parameter containing:
tensor([-0.1283], requires_grad=True)


In [12]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1459, -0.1894, -0.3744, -0.0159,  0.3304]], requires_grad=True), Parameter containing:
tensor([-0.1283], requires_grad=True)]


In [9]:
%pip install torchinfo

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from torchinfo import summary # type: ignore
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

* Building a model using 2 hidden layer

In [ ]:
import torch
from torch import nn

# Define a custom model class that inherits from PyTorch's base nn.Module
class Model_V2(nn.Module):
    def __init__(self, in_features):
        super().__init__()  # Initialize parent class (nn.Module)

        # Creating two hidden layer
        self.layer1 = nn.Linear(in_features=in_features,
                                out_features=3)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(in_features=3,
                                out_features=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, X):
        f = self.layer1(X)
        r = self.relu(f)
        z = self.layer2(r)
        y_pred = self.sigmoid(z)
        return y_pred


In [17]:
# Create a dummy dataset
X_train = torch.rand(10, 5)

# Create model
model = Model_V2(X_train.shape[1])

# Call the forward pass
# model.foward(X) -> this not recommended
model(X_train) # Recommended by PyTorch

tensor([[0.4710],
        [0.4635],
        [0.4591],
        [0.4763],
        [0.4737],
        [0.4502],
        [0.4624],
        [0.4700],
        [0.4804],
        [0.4788]], grad_fn=<SigmoidBackward0>)

In [19]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.0795,  0.1676, -0.1040,  0.0914,  0.4159],
        [-0.2198,  0.3457,  0.4003,  0.0244,  0.1384],
        [-0.3484,  0.1516,  0.0427,  0.3061,  0.1286]], requires_grad=True), Parameter containing:
tensor([ 0.2297,  0.2334, -0.1421], requires_grad=True), Parameter containing:
tensor([[-0.1296, -0.1486, -0.0779]], requires_grad=True), Parameter containing:
tensor([0.0164], requires_grad=True)]


* Using sequentail container

In [20]:
import torch
from torch import nn

# Define the model using Sequential
class Model_V3(nn.Module):
    def __init__(self, in_features):
        super().__init__()

        # Sequentially stack layers and activations
        self.network = nn.Sequential(
            nn.Linear(in_features=in_features, out_features=3),  # Layer 1
            nn.ReLU(),                                           # Activation
            nn.Linear(in_features=3, out_features=1),            # Layer 2
            nn.Sigmoid()                                         # Activation
        )

    def forward(self, X):
        y_pred = self.network(X)  # Pass input through the Sequential container
        return y_pred

In [21]:
# Create a dummy dataset
X_train = torch.rand(10, 5)

# Create model
model = Model_V3(X_train.shape[1])

# Call the forward pass
# model.foward(X) -> this not recommended
model(X_train) # Recommended by PyTorch

tensor([[0.6089],
        [0.6294],
        [0.6556],
        [0.6667],
        [0.6328],
        [0.6769],
        [0.6121],
        [0.5831],
        [0.5996],
        [0.6722]], grad_fn=<SigmoidBackward0>)