In [69]:
# 1. import dataset -> Done
# 2. preprocess -> Done
# 3. train test split -> Done
# 4. scale -> Done
# 5. encode label -> Done
# 6. build model -> Done
# 7. implement dataset and dataLoader -> Done
# 8. Train model ->

In [70]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [71]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [72]:
print(df.shape)

(569, 33)


In [73]:
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

In [74]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [75]:
print(df.shape)

(569, 31)


In [76]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:,1:], # 0th column for test
    df.iloc[:,0],
    test_size=0.2,
    random_state=42,
) # dataset will be in pandas

In [77]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>


In [78]:
print(X_train.shape); print(X_test.shape)

(455, 30)
(114, 30)


In [79]:
print(y_train.shape, y_test.shape)

(455,) (114,)


In [80]:
# Scaling : scale to value between -3 to 3
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [81]:
print(type(X_train))

<class 'numpy.ndarray'>


In [82]:
print(X_train[3])

[-0.98179678  1.41622208 -0.98258746 -0.86694414  0.05938999 -0.59678772
 -0.82020317 -0.84511471  0.31326409  0.07404147 -0.53850473  0.53647286
 -0.65795    -0.49659014  0.0654747  -0.82240418 -0.68556537 -0.89848456
  0.12329928 -0.43154667 -0.8291973   1.59353039 -0.87357215 -0.74294685
  0.79662437 -0.7293916  -0.77494969 -0.80948314  0.79892783 -0.1344968 ]


In [83]:
print(y_train[:3])

68     B
181    M
63     B
Name: diagnosis, dtype: object


In [84]:
# Encoding: Encode into 0 & 1
encode = LabelEncoder()
y_train = encode.fit_transform(y_train)
y_test = encode.transform(y_test)

In [85]:
print(y_train[:3]); print(); print(y_train[:3])

[0 1 0]

[0 1 0]


In [86]:
A = np.array([1, 2, 3, 4, 5])
A_tensor = torch.from_numpy(A.astype(np.float32)) # dependent
B = np.array([1, 2, 3, 4, 5])
B_tensor = torch.tensor(B, dtype=torch.float32) # independent
print(A_tensor, A_tensor.dtype)
print()
print(B_tensor, B_tensor.dtype)

tensor([1., 2., 3., 4., 5.]) torch.float32

tensor([1., 2., 3., 4., 5.]) torch.float32


In [87]:
A = np.array([5, 6, 7])
print(A_tensor)

tensor([1., 2., 3., 4., 5.])


In [88]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [89]:
print(type(X_train_tensor))

<class 'torch.Tensor'>


In [90]:
X_train.shape

(455, 30)

In [91]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0] # return total number of training example

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]


In [92]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [93]:
len(train_dataset)

455

In [94]:
train_dataset[2]

(tensor([-1.4000, -1.2496, -1.3452, -1.1098, -1.3326, -0.3074, -0.3656, -0.6965,
          1.9303,  0.9544,  0.0275,  1.9631, -0.1210, -0.3508,  0.5728,  0.7395,
          0.3207,  0.5895,  2.6150,  0.7189, -1.2953, -1.0408, -1.2452, -0.9997,
         -1.4387, -0.5486, -0.6449, -0.9702,  0.5976,  0.0579]),
 tensor(0.))

In [95]:
train_dataset[2][0].shape

torch.Size([30])

In [96]:
train_dataLoader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)
test_dataLoader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=True
)

In [97]:
len(train_dataLoader)

15

In [98]:
for batch_features, batch_labels in test_dataLoader:
    print(batch_features)
    print(batch_labels)
    print("-" * 50)

tensor([[-5.9957e-01, -8.2956e-01, -6.1461e-01, -5.9533e-01,  1.0685e-01,
         -6.0995e-01, -5.9697e-01, -7.7988e-01,  9.7612e-01, -4.2722e-01,
         -6.1841e-01,  9.6670e-02, -6.8502e-01, -5.0676e-01, -3.3407e-01,
         -4.0435e-01, -3.9718e-01, -7.7410e-01, -1.0456e-01, -4.3586e-01,
         -5.3373e-01, -1.0493e-01, -5.7961e-01, -5.4508e-01,  2.6750e-01,
         -3.3868e-01, -2.2898e-01, -5.8023e-01,  7.5137e-01, -2.5958e-01],
        [ 7.5380e-01, -9.0355e-02,  7.1692e-01,  6.5413e-01, -5.1008e-01,
         -2.2512e-01, -5.8933e-02,  4.5978e-01,  2.9870e-01, -1.0299e+00,
          6.9643e-01,  3.4799e-01,  6.1420e-01,  5.7792e-01, -2.8364e-01,
         -5.0330e-02, -2.0441e-01,  6.5945e-01,  4.1221e-02, -1.1762e-01,
          7.9378e-01,  1.2616e-01,  7.0781e-01,  6.7545e-01, -6.3894e-01,
         -2.6376e-01, -2.0459e-01,  5.0905e-01, -1.5063e-01, -6.4997e-01],
        [ 3.4043e-01, -4.4940e-01,  4.6584e-01,  1.6619e-01,  2.7148e+00,
          2.3807e+00,  1.9640e+00,  

In [99]:
# Buidling the Model
from torch import nn

class Model(nn.Module):
    def __init__(self, in_features):
        super().__init__()
        self.layer1 = nn.Linear(in_features, 60)
        self.layer2 = nn.Linear(60, 30)
        self.layer3 = nn.Linear(30, 1)
        self.relu = nn.ReLU()
        self.leakyrelu= nn.LeakyReLU(negative_slope=0.01)
        self.sigmoid = nn.Sigmoid()

    def forward(self, X):
        y_pred = self.layer1(X)
        y_pred = self.relu(y_pred)
        y_pred = self.layer2(y_pred)
        y_pred = self.leakyrelu(y_pred)
        y_pred = self.layer3(y_pred)
        y_pred = self.sigmoid(y_pred)

        return y_pred


In [100]:
# Hyper parameter
import torch
torch.manual_seed(42)
lr = 0.1
epochs=50

# Create empty loss list to track values
train_loss_values = []
test_loss_values = []
epoch_count = []

# Create Model
model=Model(X_train_tensor.shape[1])

# Create a loss function
loss_fn = nn.BCELoss()

# Create optimizers
optimizer = torch.optim.SGD(params=model.parameters(),
                            lr=lr)


for epoch in range(epochs):

    # put the model in training mode
    model.train()
    for batch_features, batch_labels in train_dataLoader:
        # forward pass
        y_pred = model(batch_features)

        # calculate loss
        loss = loss_fn(y_pred, batch_labels.view(-1,1))

        # clear gradients
        optimizer.zero_grad()

        # backward pass
        loss.backward()

        # update parameters
        optimizer.step()

        # put model in evaluation mode
    model.eval()

    with torch.inference_mode():
        for batch_features, batch_labels in test_dataLoader:
        # forward pass on test
            y_test_pred = model(batch_features)

            # calculate test loss
            test_loss = loss_fn(y_test_pred, batch_labels.view(-1,1))

            if epoch % 10 == 0:
                epoch_count.append(epoch)
                train_loss_values.append(loss.detach().numpy())
                test_loss_values.append(test_loss.detach().numpy())
                print(f"Epoch: {epoch} | BCE Train Loss: {loss} | BCE Test Loss: {test_loss} ")

Epoch: 0 | BCE Train Loss: 0.6258930563926697 | BCE Test Loss: 0.594404399394989 


Epoch: 0 | BCE Train Loss: 0.6258930563926697 | BCE Test Loss: 0.6139651536941528 
Epoch: 0 | BCE Train Loss: 0.6258930563926697 | BCE Test Loss: 0.5916479825973511 
Epoch: 0 | BCE Train Loss: 0.6258930563926697 | BCE Test Loss: 0.6248342990875244 
Epoch: 10 | BCE Train Loss: 0.013659660704433918 | BCE Test Loss: 0.050189994275569916 
Epoch: 10 | BCE Train Loss: 0.013659660704433918 | BCE Test Loss: 0.09959285706281662 
Epoch: 10 | BCE Train Loss: 0.013659660704433918 | BCE Test Loss: 0.026972534134984016 
Epoch: 10 | BCE Train Loss: 0.013659660704433918 | BCE Test Loss: 0.058745913207530975 
Epoch: 20 | BCE Train Loss: 0.12607645988464355 | BCE Test Loss: 0.0945611447095871 
Epoch: 20 | BCE Train Loss: 0.12607645988464355 | BCE Test Loss: 0.05884971842169762 
Epoch: 20 | BCE Train Loss: 0.12607645988464355 | BCE Test Loss: 0.02074805088341236 
Epoch: 20 | BCE Train Loss: 0.12607645988464355 | BCE Test Loss: 0.012704690918326378 
Epoch: 30 | BCE Train Loss: 0.021675333380699158 | BCE T

In [101]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_dataLoader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9844


* Clean & Engineered Code 

In [ ]:
import torch
from torch import nn

# -------------------------
# Define the Model
# -------------------------
class Model(nn.Module):
    def __init__(self, in_features):
        super().__init__()
        self.layer1 = nn.Linear(in_features, 60)
        self.layer2 = nn.Linear(60, 30)
        self.layer3 = nn.Linear(30, 1)   # raw logits
        self.relu = nn.ReLU()
        self.leakyrelu = nn.LeakyReLU(negative_slope=0.01)

    def forward(self, X):
        x = self.layer1(X)
        x = self.relu(x)
        x = self.layer2(x)
        x = self.leakyrelu(x)
        x = self.layer3(x)   #  no sigmoid here
        return x

In [ ]:
# -------------------------
# Hyperparameters
# -------------------------
torch.manual_seed(42)
lr = 0.001
epochs = 50

# Create Model
model = Model(X_train_tensor.shape[1])

# Loss function (stable version)
loss_fn = nn.BCEWithLogitsLoss()

# Optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=lr)

# Track metrics
train_loss_values = []
test_loss_values = []
epoch_count = []


# -------------------------
# Training Loop
# -------------------------
for epoch in range(epochs):
    # ----- TRAIN -----
    model.train()
    train_loss = 0
    for batch_features, batch_labels in train_dataLoader:
        # Forward pass (raw logits)
        y_pred = model(batch_features).squeeze(1)
        loss = loss_fn(y_pred, batch_labels.float())

        # Backward + Optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    train_loss /= len(train_dataLoader)

    # ----- EVAL -----
    model.eval()
    test_loss = 0
    correct = 0
    total = 0
    with torch.inference_mode():
        for batch_features, batch_labels in test_dataLoader:
            y_test_pred = model(batch_features).squeeze(1)
            loss = loss_fn(y_test_pred, batch_labels.float())
            test_loss += loss.item()

            # Convert logits → probs → binary predictions
            preds = (torch.sigmoid(y_test_pred) > 0.5).int()
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

    test_loss /= len(test_dataLoader)
    accuracy = correct / total

    # ----- LOGGING -----
    if epoch % 10 == 0 or epoch == epochs - 1:
        epoch_count.append(epoch)
        train_loss_values.append(train_loss)
        test_loss_values.append(test_loss)
        print(f"Epoch {epoch:03d} | "
              f"Train Loss: {train_loss:.4f} | "
              f"Test Loss: {test_loss:.4f} | "
              f"Acc: {accuracy:.4f}")
